import{PERMISSION_CATALOG,normalizePermissions,fullPermissions}from'./permissions.js'
const n=v=>Number(v||0),sid=v=>v==null?'':String(v),dateOf=r=>r?.date||r?.paid_at||r?.adjustment_date||r?.return_date||r?.created_at||null
const sum=(rows,key)=>rows.reduce((s,r)=>s+n(typeof key==='function'?key(r):r[key]),0),idx=rows=>new Map((rows||[]).map(r=>[sid(r.id),r]))
const parse=value=>{if(value&&typeof value==='object')return value;if(typeof value==='string'){try{return JSON.parse(value)}catch{return{description:value}}}return{}}
const words=value=>String(value||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())
const moduleOf=(action,target)=>{const a=String(action||'').toLowerCase(),t=String(target||'').toLowerCase();if(/login|logout|security|password/.test(a))return'Security';if(/backup|restore/.test(a))return'Backup';if(/permission|privilege|user_disabled/.test(a+t))return'User Privileges';if(/sms/.test(a+t))return'SMS';if(/cheque/.test(a+t))return'Cheques';if(/payment|commission|bank|journal/.test(a+t))return'Finance';if(/purchase/.test(a+t))return'Purchases';if(/invoice/.test(a+t))return'Invoices';if(/order/.test(a+t))return'Orders';if(/return/.test(a+t))return'Returns';if(/stock|product|inventory|beginning/.test(a+t))return'Inventory';if(/customer/.test(a+t))return'Customers';if(/vendor/.test(a+t))return'Vendors';if(/employee|rep/.test(a+t))return'Employees';return words(target||'System')}
const critical=a=>/delete|revers|return_cheque|cheque_return|permission|privilege|restore|stock.*adjust|mismatch/.test(String(a||'').toLowerCase())
const actor=r=>r?.user_name||r?.display_name||r?.user_email||r?.created_by||'-'

export function normalizeAuditLogs(logs=[],privileges=[]){
 const roles=new Map(privileges.map(u=>[String(u.email||'').toLowerCase(),u.is_super_admin?'Super Admin':words(u.user_type||'User')]))
 return logs.map(log=>{const d=parse(log.details),action=String(log.action||'activity'),user=actor(log),email=String(log.user_email||log.created_by||'').toLowerCase(),oldValue=log.old_values??d.old_values??d.before??d.previous??null,newValue=log.new_values??d.new_values??d.after??d.corrected??null,reference=log.reference_no||d.reference_no||d.reference||d.order||d.invoice||d.purchase||log.target_label||'-';return{
  id:log.id,date:log.created_at,user,userEmail:email,userRole:roles.get(email)||'-',action,module:log.module||moduleOf(action,log.target_type),recordType:log.target_type||'-',reference,description:d.description||d.message||(typeof log.details==='string'?log.details:'')||words(action),oldValue,newValue,reason:log.reason||d.reason||d.notes||'-',ipDevice:log.ip_address||d.ip_address||d.device||'-',amount:n(log.amount??d.amount??d.payment_amount??d.purchase_total??d.total_amount),party:d.party||d.customer||d.vendor||d.rep||d.customer_name||d.vendor_name||d.rep_name||'-',paymentMethod:d.payment_method||d.method||'-',bank:d.bank||d.bank_name||'-',createdDate:d.original_created_at||d.created_at||null,raw:log,details:d,critical:critical(action)
 }})
}

export function buildInventoryActivity(raw){
 const products=idx(raw.products),events=[]
 const add=(productId,event)=>{const p=products.get(sid(productId));if(!p)return;events.push({id:event.id,productId,productCode:p.code||'-',productName:p.name||'-',...event})}
 ;(raw.purchaseItems||[]).forEach(i=>{const p=raw.purchaseMap.get(sid(i.purchase_id));if(!p)return;add(i.product_id,{id:`purchase-${i.id}`,date:dateOf(p),transactionType:'Purchase',reference:p.ref_no||`PUR-${sid(p.id).slice(0,8)}`,quantityIn:n(i.quantity),quantityOut:0,user:p.created_by||'-',reason:'Stock received'})})
 ;(raw.purchaseItems||[]).forEach(i=>{const p=raw.purchaseMap.get(sid(i.purchase_id));if(!p||String(p.status).toLowerCase()!=='reversed')return;add(i.product_id,{id:`reversal-${i.id}`,date:p.reversed_at||p.updated_at||dateOf(p),transactionType:'Purchase Reversal',reference:p.ref_no||`PUR-${sid(p.id).slice(0,8)}`,quantityIn:0,quantityOut:n(i.quantity),user:p.reversed_by||'-',reason:p.reversal_reason||'Purchase reversed'})})
 ;(raw.invoiceItems||[]).forEach(i=>{const inv=raw.invoiceMap.get(sid(i.invoice_id));if(inv)add(i.product_id,{id:`invoice-${i.id}`,date:dateOf(inv),transactionType:'Invoice / Sale',reference:inv.invoice_number?`INV-${String(inv.invoice_number).padStart(4,'0')}`:sid(inv.id).slice(0,8),quantityIn:0,quantityOut:n(i.quantity),user:inv.created_by||'-',reason:'Product sold'})})
 ;(raw.returnItems||[]).forEach(i=>{const ret=raw.returnMap.get(sid(i.return_id));if(ret)add(i.product_id,{id:`return-${i.id}`,date:dateOf(ret),transactionType:'Sales Return',reference:ret.return_number?`RET-${String(ret.return_number).padStart(4,'0')}`:sid(ret.id).slice(0,8),quantityIn:n(i.quantity),quantityOut:0,user:ret.created_by||'-',reason:ret.reason||'Customer return'})})
 ;(raw.beginningItems||[]).forEach(i=>{const bs=raw.beginningMap.get(sid(i.beginning_stock_id));if(bs)add(i.product_id,{id:`beginning-${i.id}`,date:dateOf(bs),transactionType:'Beginning Stock',reference:bs.ref_no||sid(bs.id).slice(0,8),quantityIn:n(i.quantity),quantityOut:0,user:bs.created_by||'-',reason:'Opening stock'})})
 ;(raw.stockAdjustments||[]).forEach(a=>{const incoming=['positive'].includes(String(a.adjustment_type)),outgoing=['negative','damage'].includes(String(a.adjustment_type));add(a.product_id,{id:`adjust-${a.id}`,date:dateOf(a),transactionType:words(a.adjustment_type||'Manual Adjustment'),reference:a.reference_no||sid(a.id).slice(0,8),quantityIn:incoming?n(a.quantity):0,quantityOut:outgoing?n(a.quantity):0,user:a.created_by||'-',reason:a.notes||'Manual stock adjustment'})})
 const groups=new Map();events.forEach(e=>groups.set(sid(e.productId),[...(groups.get(sid(e.productId))||[]),e]));const result=[]
 groups.forEach((rows,key)=>{let stock=n(products.get(key)?.stock);[...rows].sort((a,b)=>new Date(b.date)-new Date(a.date)).forEach(row=>{row.stockAfter=stock;row.stockBefore=stock-n(row.quantityIn)+n(row.quantityOut);stock=row.stockBefore;result.push(row)})})
 return result.sort((a,b)=>new Date(b.date)-new Date(a.date))
}

export function buildAdminSystemReports(raw){
 const audit=normalizeAuditLogs(raw.auditLogs,raw.userPrivileges),purchaseMap=idx(raw.purchases),invoiceMap=idx(raw.invoices),returnMap=idx(raw.returns),beginningMap=idx(raw.beginningStock)
 const inventory=buildInventoryActivity({...raw,purchaseMap,invoiceMap,returnMap,beginningMap})
 const destructive=/delete|cancel|revers|void/i,financial=/payment|commission|cheque|bank|journal|purchase_revers/i
 const deleted=audit.filter(r=>destructive.test(r.action)).map(r=>({...r,transactionType:words(r.recordType),originalAmount:r.amount,originalCreatedDate:r.createdDate,performedBy:r.user}))
 ;(raw.purchases||[]).filter(p=>String(p.status).toLowerCase()==='reversed'&&!deleted.some(r=>sid(r.raw?.target_id)===sid(p.id))).forEach(p=>deleted.push({id:`purchase-${p.id}`,date:p.reversed_at||p.updated_at||dateOf(p),transactionType:'Purchase',reference:p.ref_no||sid(p.id).slice(0,8),party:p.vendor_name||'-',originalAmount:n(p.total_amount),action:'reverse_purchase',reason:p.reversal_reason||'-',performedBy:p.reversed_by||'-',originalCreatedDate:p.created_at,critical:true}))
 const reversalInventory=new Map();inventory.filter(r=>r.transactionType==='Purchase Reversal').forEach(r=>{const key=String(r.reference||'').toLowerCase();reversalInventory.set(key,[...(reversalInventory.get(key)||[]),r])})
 deleted.forEach(row=>{if(!/purchase/i.test(`${row.transactionType} ${row.action}`))return;const items=reversalInventory.get(String(row.reference||'').toLowerCase())||[];if(!items.length)return;row.productsAffected=items.map(x=>`${x.productCode} ${x.productName}`).join(', ');row.quantityReversed=sum(items,'quantityOut');row.stockBefore=items.map(x=>`${x.productCode}: ${x.stockBefore}`).join('; ');row.stockAfter=items.map(x=>`${x.productCode}: ${x.stockAfter}`).join('; ')})
 const financialActivity=audit.filter(r=>financial.test(r.action)||r.module==='Finance').map(r=>({...r}))
 const sms=[...(raw.bulkSms||[]).map(x=>({id:`bulk-${x.id}`,date:x.created_at,smsType:'Bulk SMS',recipient:`${(x.numbers||[]).length} recipients`,party:x.campaign_name||'-',phone:(x.numbers||[]).join(', '),template:x.campaign_name||'-',messagePreview:String(x.content||'').slice(0,100),status:x.status||'pending',serverReference:JSON.stringify(x.server_refs||''),sentBy:x.created_by||'-',isBulk:true})),...(raw.repSms||[]).map(x=>({id:`rep-${x.id}`,date:x.created_at,smsType:'Rep Commission Payment SMS',recipient:x.rep_name||'-',party:x.rep_name||'-',phone:x.phone_number||'-',template:'Rep payment',messagePreview:String(x.message||'').slice(0,100),status:x.status||'-',serverReference:x.server_reference||'-',sentBy:x.created_by||'-'})),...audit.filter(x=>/sms/i.test(x.action)&&!/^Rep Payment SMS Sent$/i.test(x.action)).map(x=>({id:`audit-sms-${x.id}`,date:x.date,smsType:words(x.action),recipient:x.party,party:x.party,phone:x.details.phone||'-',template:x.details.template||'-',messagePreview:String(x.details.message||x.description||'').slice(0,100),status:x.details.status||'-',serverReference:x.details.server_reference||'-',sentBy:x.user}))]
 const employeeMap=idx(raw.employees),privileges=(raw.userPrivileges||[]).flatMap(u=>{const permissions=u.is_super_admin?fullPermissions():normalizePermissions(u.permissions);return PERMISSION_CATALOG.map(m=>({id:`${u.id}-${m.id}`,userId:u.id,user:u.email,displayName:u.display_name||'-',userType:u.user_type||'user',employee:u.employees?.name||employeeMap.get(sid(u.employee_id))?.name||'-',active:u.is_active!==false,superAdmin:!!u.is_super_admin,module:m.label,supported:new Set(m.actions.map(a=>a.id)),view:permissions[m.id]?.view,create:permissions[m.id]?.create,edit:permissions[m.id]?.edit,delete:permissions[m.id]?.delete,print:permissions[m.id]?.print,export:permissions[m.id]?.export}))})
 const security=audit.filter(r=>r.module==='Security'||/login|logout|password|user_disabled/i.test(r.action)),backup=audit.filter(r=>r.module==='Backup'||/backup|restore/i.test(r.action)).map(r=>({...r,backupType:r.details.backup_type||'Application export',scope:r.details.scope||r.details.tables||'-',status:r.details.status||'Recorded',fileName:r.details.file_name||'-'}))
 return{audit,userActivity:audit,deleted,financialActivity,inventory,sms,privileges,security,backup,important:audit.filter(r=>r.critical||financial.test(r.action)).slice(0,100),permissionCatalog:PERMISSION_CATALOG}
}
export const adminReportMath={n,sum,words,critical}
