export const amount = value => Number(value || 0)
export const transactionDate = row => typeof row === 'string' || row instanceof Date ? row : row?.date || row?.invoice_date || row?.order_date || row?.return_date || row?.paid_at || row?.created_at || null
export const valid = row => !['draft','cancelled','canceled','deleted','void'].includes(String(row?.status || '').toLowerCase()) && !row?.deleted_at

export function buildCustomerReport(raw, from, to) {
  const start = new Date(`${from}T00:00:00`), end = new Date(`${to}T23:59:59.999`), today = new Date()
  const paymentsByInvoice = new Map(), returnsByInvoice = new Map()
  raw.payments.filter(valid).forEach(p => paymentsByInvoice.set(p.invoice_id,(paymentsByInvoice.get(p.invoice_id)||0)+amount(p.amount)))
  raw.returns.filter(valid).forEach(r => r.invoice_id&&returnsByInvoice.set(r.invoice_id,(returnsByInvoice.get(r.invoice_id)||0)+amount(r.total_amount)))
  const rows=raw.customers.map(customer=>{
    const invoices=raw.invoices.filter(x=>x.customer_id===customer.id&&valid(x)), allOrders=raw.orders.filter(x=>x.customer_id===customer.id&&!x.deleted_at), orders=allOrders.filter(valid), returns=raw.returns.filter(x=>x.customer_id===customer.id&&valid(x)), cheques=raw.cheques.filter(x=>x.customer_id===customer.id&&valid(x))
    const periodInvoices=invoices.filter(x=>{const d=new Date(transactionDate(x));return d>=start&&d<=end}), periodOrders=orders.filter(x=>{const d=new Date(transactionDate(x));return d>=start&&d<=end}), periodReturns=returns.filter(x=>{const d=new Date(transactionDate(x));return d>=start&&d<=end})
    const invoiceIds=new Set(invoices.map(x=>x.id)), payments=raw.payments.filter(x=>invoiceIds.has(x.invoice_id)&&valid(x)), periodPayments=payments.filter(x=>{const d=new Date(transactionDate(x));return d>=start&&d<=end})
    const outstandingInvoices=invoices.map(invoice=>{const paid=paymentsByInvoice.get(invoice.id)||0,credit=returnsByInvoice.get(invoice.id)||0,balance=Math.max(0,amount(invoice.total_amount)-paid-credit),date=transactionDate(invoice),days=Math.max(0,Math.floor((today-new Date(date))/86400000));return{...invoice,paid,credit,balance,date,days,bucket:days<=30?'Current':days<=60?'31-60':days<=90?'61-90':days<=120?'91-120':'Over 120'}}).filter(x=>x.balance>0)
    const gross=periodInvoices.reduce((s,x)=>s+amount(x.total_amount),0), returnValue=periodReturns.reduce((s,x)=>s+amount(x.total_amount),0), paid=periodPayments.reduce((s,x)=>s+amount(x.amount),0), outstanding=outstandingInvoices.reduce((s,x)=>s+x.balance,0), creditLimit=amount(customer.credit_limit), available=creditLimit-outstanding
    const itemQty=periodInvoices.flatMap(x=>raw.invoiceItems.filter(i=>i.invoice_id===x.id)).reduce((s,x)=>s+amount(x.quantity),0), last=(xs)=>[...xs].sort((a,b)=>new Date(transactionDate(b))-new Date(transactionDate(a)))[0]
    const rep=raw.employees.find(x=>x.id===(customer.rep_id||customer.sales_rep_id))
    const statuses=periodOrders.reduce((a,x)=>{const k=String(x.status||'pending').toLowerCase();a[k]=(a[k]||0)+1;return a},{})
    const usage=creditLimit?outstanding/creditLimit*100:0, creditStatus=!creditLimit?'No Credit Limit':outstanding>creditLimit?'Limit Exceeded':outstanding===creditLimit?'Limit Reached':usage>=75?'Near Limit':'Good Standing'
    return{...customer,repName:rep?.name||rep?.full_name||'—',orders:periodOrders,invoices:periodInvoices,returns:periodReturns,payments:periodPayments,cheques,outstandingInvoices,totalOrders:periodOrders.length,pending:statuses.pending||0,confirmed:statuses.confirmed||0,delivered:statuses.delivered||0,cancelled:allOrders.filter(x=>{const d=new Date(transactionDate(x));return d>=start&&d<=end&&['cancelled','canceled'].includes(String(x.status).toLowerCase())}).length,totalInvoices:periodInvoices.length,quantity:itemQty,gross,returnValue,net:gross-returnValue,paid,outstanding,creditLimit,available,creditStatus,usage,lastOrder:last(orders),lastInvoice:last(invoices),lastPayment:last(payments),lastReturn:last(returns),lastCheque:last(cheques),oldest:outstandingInvoices.sort((a,b)=>new Date(a.date)-new Date(b.date))[0],maxAging:Math.max(0,...outstandingInvoices.map(x=>x.days)),chequeInHand:cheques.filter(x=>x.status==='in_hand').reduce((s,x)=>s+amount(x.amount),0),chequeDeposited:cheques.filter(x=>x.status==='deposited').reduce((s,x)=>s+amount(x.amount),0),chequeReturned:cheques.filter(x=>x.status==='returned').reduce((s,x)=>s+amount(x.amount),0)}
  })
  return rows
}

export function buildStatement(raw,customerId,from,to){const start=new Date(`${from}T00:00:00`),end=new Date(`${to}T23:59:59.999`),invoiceMap=new Map(raw.invoices.map(x=>[x.id,x])),tx=[]
 raw.invoices.filter(x=>x.customer_id===customerId&&valid(x)).forEach(x=>tx.push({date:transactionDate(x),created:x.created_at,reference:x.invoice_number||x.id,type:'Invoice',description:'Sales invoice',debit:amount(x.total_amount),credit:0,status:x.status||'posted'}))
 raw.payments.filter(x=>invoiceMap.get(x.invoice_id)?.customer_id===customerId&&valid(x)).forEach(x=>tx.push({date:transactionDate(x),created:x.created_at,reference:x.reference||x.receipt_number||x.id,type:'Payment',description:`Payment received${x.method?' · '+x.method:''}`,debit:0,credit:amount(x.amount),method:x.method,status:x.status||'received'}))
 raw.returns.filter(x=>x.customer_id===customerId&&valid(x)).forEach(x=>tx.push({date:transactionDate(x),created:x.created_at,reference:x.return_number||x.id,type:'Return',description:'Customer return / credit',debit:0,credit:amount(x.total_amount),status:x.status||'approved'}))
 raw.cheques.filter(x=>x.customer_id===customerId&&x.status==='returned').forEach(x=>tx.push({date:x.returned_at||x.updated_at||x.created_at,created:x.created_at,reference:x.cheque_number||x.id,type:'Cheque Returned',description:'Returned cheque reversal',debit:amount(x.amount),credit:0,method:'cheque',status:'returned'}))
 tx.sort((a,b)=>new Date(a.date)-new Date(b.date));const opening=tx.filter(x=>new Date(x.date)<start).reduce((s,x)=>s+x.debit-x.credit,0);let balance=opening;const rows=tx.filter(x=>new Date(x.date)>=start&&new Date(x.date)<=end).map(x=>({...x,balance:balance+=x.debit-x.credit}));return{rows,opening,debits:rows.reduce((s,x)=>s+x.debit,0),credits:rows.reduce((s,x)=>s+x.credit,0),closing:balance}}
