const n=v=>Number(v||0),sid=v=>v==null?'':String(v),status=(v,d='pending')=>String(v||d).toLowerCase(),when=r=>r?.return_date||r?.order_date||r?.invoice_date||r?.date||r?.created_at||null
const idx=rows=>new Map((rows||[]).map(r=>[sid(r.id),r])),total=(rows,key)=>rows.reduce((s,r)=>s+n(typeof key==='function'?key(r):r[key]),0)
const days=(a,b)=>!a||!b?null:Math.max(0,Math.floor((new Date(b)-new Date(a))/86400000)),between=(v,r)=>v&&new Date(v)>=new Date(`${r.from}T00:00:00`)&&new Date(v)<=new Date(`${r.to}T23:59:59.999`)
const docNo=(p,v,f='-')=>v!=null&&v!==''?`${p}-${String(v).padStart(4,'0')}`:f,contains=(v,q)=>!q||String(v||'').toLowerCase().includes(String(q).trim().toLowerCase())
const actor=r=>r?.user_name||r?.display_name||r?.user_email||r?.created_by||r?.updated_by||'-',auditActor=(logs,targetId,actions)=>actor((logs||[]).find(l=>sid(l.target_id)===sid(targetId)&&actions.includes(status(l.action)))||{})
const deliveryStatus=o=>['pending','confirmed'].includes(status(o.status))?'pending':status(o.status)==='converted'?'invoiced':status(o.status)

export function buildReturnsDeliveryReports(raw,range,filters={}){
 const customers=idx(raw.customers),employees=idx(raw.employees),products=idx(raw.products),invoices=idx(raw.invoices),orders=idx(raw.orders),returnItems=new Map(),invoiceItems=new Map(),paymentsByInvoice=new Map(),creditsByInvoice=new Map()
 ;(raw.returnItems||[]).forEach(x=>returnItems.set(sid(x.return_id),[...(returnItems.get(sid(x.return_id))||[]),x]));(raw.invoiceItems||[]).forEach(x=>invoiceItems.set(sid(x.invoice_id),[...(invoiceItems.get(sid(x.invoice_id))||[]),x]));(raw.invoicePayments||[]).forEach(x=>paymentsByInvoice.set(sid(x.invoice_id),(paymentsByInvoice.get(sid(x.invoice_id))||0)+n(x.amount)));(raw.returns||[]).forEach(x=>creditsByInvoice.set(sid(x.invoice_id),(creditsByInvoice.get(sid(x.invoice_id))||0)+n(x.total_amount)))
 const orderForInvoice=i=>(i&&orders.get(sid(i.order_id)))||(raw.orders||[]).find(o=>sid(o.invoice_id)===sid(i?.id))
 const returnHeaders=(raw.returns||[]).filter(r=>{const i=invoices.get(sid(r.invoice_id)),o=orderForInvoice(i);return between(when(r),range)&&(!filters.customer||sid(r.customer_id)===sid(filters.customer))&&(!filters.rep||sid(i?.rep_id||o?.rep_id)===sid(filters.rep))&&(!filters.returnStatus||status(r.status,'completed')===status(filters.returnStatus))&&contains(docNo('INV',i?.invoice_number,i?.id),filters.invoice)&&contains(docNo('ORD',o?.order_number,o?.id),filters.order)})
 const detailedReturns=returnHeaders.flatMap(r=>{const i=invoices.get(sid(r.invoice_id)),o=orderForInvoice(i),c=customers.get(sid(r.customer_id||i?.customer_id)),rep=employees.get(sid(i?.rep_id||o?.rep_id)),all=returnItems.get(sid(r.id))||[],subtotal=all.reduce((s,x)=>s+n(x.total??n(x.quantity)*n(x.price)),0);return all.filter(x=>!filters.product||sid(x.product_id)===sid(filters.product)).map(x=>{const p=products.get(sid(x.product_id)),line=n(x.total??n(x.quantity)*n(x.price)),allocated=subtotal&&r.total_amount!=null?line/subtotal*n(r.total_amount):line;return{id:`${r.id}-${x.id}`,returnId:r.id,customerId:r.customer_id||i?.customer_id,productId:x.product_id,repId:i?.rep_id||o?.rep_id,invoiceId:i?.id,orderId:o?.id,date:when(r),returnNumber:docNo('RET',r.return_number,`RET-${sid(r.id).slice(0,8)}`),customer:c?.name||'-',phone:c?.phone||c?.phone1||'-',invoiceNumber:i?docNo('INV',i.invoice_number,`INV-${sid(i.id).slice(0,8)}`):'-',orderNumber:o?docNo('ORD',o.order_number,`ORD-${sid(o.id).slice(0,8)}`):'-',salesRep:rep?.name||rep?.full_name||'-',productCode:p?.code||'-',productName:p?.name||'-',quantity:n(x.quantity),unitPrice:n(x.price),returnAmount:allocated,reason:r.reason||'-',status:status(r.status,'completed'),stockUpdated:r.stock_updated===false?'No':'Yes',createdBy:r.created_by||auditActor(raw.auditLogs,r.id,['create_return','return_created']),createdAt:r.created_at}})})
 const invoiceRows=(raw.invoices||[]).filter(i=>!['draft','cancelled','canceled','deleted','void'].includes(status(i.status,'posted'))&&!i.deleted_at&&between(when(i),range)&&(!filters.customer||sid(i.customer_id)===sid(filters.customer))&&(!filters.rep||sid(i.rep_id)===sid(filters.rep))&&contains(docNo('INV',i.invoice_number,i.id),filters.invoice)&&(!filters.product||(invoiceItems.get(sid(i.id))||[]).some(x=>sid(x.product_id)===sid(filters.product))))
 const invoiceSalesTotal=filters.product?invoiceRows.reduce((s,i)=>s+(invoiceItems.get(sid(i.id))||[]).filter(x=>sid(x.product_id)===sid(filters.product)).reduce((a,x)=>a+n(x.total??n(x.quantity)*n(x.price)),0),0):total(invoiceRows,'total_amount')
 const salesCustomer=new Map(),salesRep=new Map(),soldProduct=new Map();invoiceRows.forEach(i=>{const c=customers.get(sid(i.customer_id)),rep=employees.get(sid(i.rep_id)),ck=sid(i.customer_id),rk=sid(i.rep_id),cr=salesCustomer.get(ck)||{customerId:ck,customer:c?.name||'-',phone:c?.phone||c?.phone1||'-',invoices:0,totalSales:0,outstanding:0};cr.invoices++;cr.totalSales+=n(i.total_amount);cr.outstanding+=Math.max(0,n(i.total_amount)-n(paymentsByInvoice.get(sid(i.id)))-n(creditsByInvoice.get(sid(i.id))));salesCustomer.set(ck,cr);const rr=salesRep.get(rk)||{repId:rk,salesRep:rep?.name||rep?.full_name||'-',invoices:0,salesValue:0};rr.invoices++;rr.salesValue+=n(i.total_amount);salesRep.set(rk,rr);(invoiceItems.get(sid(i.id))||[]).filter(x=>!filters.product||sid(x.product_id)===sid(filters.product)).forEach(x=>{const p=products.get(sid(x.product_id)),key=sid(x.product_id),row=soldProduct.get(key)||{productId:key,productCode:p?.code||'-',productName:p?.name||'-',quantitySold:0};row.quantitySold+=n(x.quantity);soldProduct.set(key,row)})})
 const byCustomer=new Map(),byProduct=new Map(),byRep=new Map();detailedReturns.forEach(r=>{const c=byCustomer.get(sid(r.customerId))||{customerId:r.customerId,customer:r.customer,phone:r.phone,ids:new Set(),quantityReturned:0,returnValue:0,lastReturnDate:null};c.ids.add(r.returnId);c.quantityReturned+=r.quantity;c.returnValue+=r.returnAmount;if(!c.lastReturnDate||new Date(r.date)>new Date(c.lastReturnDate))c.lastReturnDate=r.date;byCustomer.set(sid(r.customerId),c);const p=byProduct.get(sid(r.productId))||{productId:r.productId,productCode:r.productCode,productName:r.productName,quantityReturned:0,returnValue:0,lastReturnDate:null};p.quantityReturned+=r.quantity;p.returnValue+=r.returnAmount;if(!p.lastReturnDate||new Date(r.date)>new Date(p.lastReturnDate))p.lastReturnDate=r.date;byProduct.set(sid(r.productId),p);const rep=byRep.get(sid(r.repId))||{repId:r.repId,salesRep:r.salesRep,ids:new Set(),returnQuantity:0,returnValue:0,customers:new Set()};rep.ids.add(r.returnId);rep.returnQuantity+=r.quantity;rep.returnValue+=r.returnAmount;rep.customers.add(sid(r.customerId));byRep.set(sid(r.repId),rep)})
 const returnsByCustomer=[...byCustomer.values()].map(r=>{const s=salesCustomer.get(sid(r.customerId))||{};return{...r,numberOfReturns:r.ids.size,totalSales:n(s.totalSales),returnPercentage:n(s.totalSales)?r.returnValue/n(s.totalSales)*100:0,outstandingBalance:n(s.outstanding)}})
 const returnsByProduct=[...new Set([...soldProduct.keys(),...byProduct.keys()])].map(key=>{const s=soldProduct.get(key)||{},r=byProduct.get(key)||{},p=products.get(key),sold=n(s.quantitySold),returned=n(r.quantityReturned);return{productId:key,productCode:s.productCode||r.productCode||p?.code||'-',productName:s.productName||r.productName||p?.name||'-',quantitySold:sold,quantityReturned:returned,netQuantitySold:sold-returned,returnValue:n(r.returnValue),returnRate:sold?returned/sold*100:0,lastReturnDate:r.lastReturnDate||null}}).filter(r=>r.quantityReturned>0)
 const returnsByRep=[...new Set([...salesRep.keys(),...byRep.keys()])].map(key=>{const s=salesRep.get(key)||{},r=byRep.get(key)||{};return{repId:key,salesRep:s.salesRep||r.salesRep||'-',invoices:n(s.invoices),salesValue:n(s.salesValue),numberOfReturns:r.ids?.size||0,returnQuantity:n(r.returnQuantity),returnValue:n(r.returnValue),returnPercentage:n(s.salesValue)?n(r.returnValue)/n(s.salesValue)*100:0,customersWithReturns:r.customers?.size||0}}).filter(r=>r.numberOfReturns)
 const returnValue=detailedReturns.map(r=>{const originalSaleValue=(invoiceItems.get(sid(r.invoiceId))||[]).filter(i=>sid(i.product_id)===sid(r.productId)).reduce((s,i)=>s+n(i.total??n(i.quantity)*n(i.price)),0);return{...r,originalSaleValue,netSaleAfterReturn:originalSaleValue-r.returnAmount}})
 const deliveryRows=(raw.orders||[]).filter(o=>{const i=invoices.get(sid(o.invoice_id)),st=deliveryStatus(o);return between(when(o),range)&&(!filters.customer||sid(o.customer_id)===sid(filters.customer))&&(!filters.rep||sid(o.rep_id)===sid(filters.rep))&&(!filters.deliveryStatus||st===status(filters.deliveryStatus))&&contains(docNo('ORD',o.order_number,o.id),filters.order)&&contains(docNo('INV',i?.invoice_number,i?.id),filters.invoice)}).map(o=>{const i=invoices.get(sid(o.invoice_id)),c=customers.get(sid(o.customer_id)),rep=employees.get(sid(o.rep_id)),st=deliveryStatus(o);return{id:o.id,date:when(o),customerId:o.customer_id,repId:o.rep_id,orderNumber:docNo('ORD',o.order_number,`ORD-${sid(o.id).slice(0,8)}`),invoiceNumber:i?docNo('INV',i.invoice_number,`INV-${sid(i.id).slice(0,8)}`):'-',orderDate:when(o),invoiceDate:when(i),customer:c?.name||'-',phone:c?.phone||c?.phone1||'-',address:o.delivery_address||o.address||c?.address||'-',salesRep:rep?.name||rep?.full_name||'-',orderTotal:n(o.total??i?.total_amount),deliveryStatus:st,deliveredDate:o.delivered_at||null,daysToDeliver:o.delivered_at?days(when(o),o.delivered_at):null,daysPending:!['delivered','cancelled'].includes(st)?days(when(o),new Date()):null,createdBy:o.created_by||auditActor(raw.auditLogs,o.id,['create_order','order_created']),deliveredBy:o.delivered_by||auditActor(raw.auditLogs,o.id,['deliver_order','order_delivered'])}})
 const pendingDelivery=deliveryRows.filter(r=>!['delivered','cancelled'].includes(r.deliveryStatus)),deliveredOrders=deliveryRows.filter(r=>r.deliveryStatus==='delivered')
 const groupDelivery=(field,name,phone=false)=>{const map=new Map();deliveryRows.forEach(r=>{const key=sid(r[field]),x=map.get(key)||{id:key,[name]:r[name],phone:phone?r.phone:undefined,totalOrders:0,deliveredOrders:0,pendingOrders:0,cancelledOrders:0,totalDeliveredValue:0,deliveryDays:[],lastDeliveryDate:null,invoices:new Set()};x.totalOrders++;if(r.invoiceNumber!=='-')x.invoices.add(r.invoiceNumber);if(r.deliveryStatus==='delivered'){x.deliveredOrders++;x.totalDeliveredValue+=r.orderTotal;if(r.daysToDeliver!=null)x.deliveryDays.push(r.daysToDeliver);if(!x.lastDeliveryDate||new Date(r.deliveredDate)>new Date(x.lastDeliveryDate))x.lastDeliveryDate=r.deliveredDate}else if(r.deliveryStatus==='cancelled')x.cancelledOrders++;else x.pendingOrders++;map.set(key,x)});return[...map.values()].map(x=>({...x,invoices:x.invoices.size,averageDeliveryTime:x.deliveryDays.length?x.deliveryDays.reduce((a,b)=>a+b,0)/x.deliveryDays.length:0}))}
 const periodKey=(v,g)=>{const d=new Date(v);if(g==='day')return d.toISOString().slice(0,10);if(g==='month')return d.toLocaleDateString(undefined,{year:'numeric',month:'short'});const m=new Date(d);m.setDate(d.getDate()-((d.getDay()+6)%7));return`Week of ${m.toISOString().slice(0,10)}`}
 const deliveryPerformance=(grouping='month')=>{const map=new Map();deliveryRows.forEach(r=>{const key=periodKey(r.orderDate,grouping),x=map.get(key)||{id:key,period:key,sortDate:r.orderDate,ordersCreated:0,ordersInvoiced:0,delivered:0,pending:0,cancelled:0,deliveryDays:[]};x.ordersCreated++;if(r.invoiceNumber!=='-')x.ordersInvoiced++;if(r.deliveryStatus==='delivered'){x.delivered++;if(r.daysToDeliver!=null)x.deliveryDays.push(r.daysToDeliver)}else if(r.deliveryStatus==='cancelled')x.cancelled++;else x.pending++;if(new Date(r.orderDate)<new Date(x.sortDate))x.sortDate=r.orderDate;map.set(key,x)});return[...map.values()].map(x=>({...x,deliveryRate:x.ordersCreated?x.delivered/x.ordersCreated*100:0,averageDeliveryDays:x.deliveryDays.length?x.deliveryDays.reduce((a,b)=>a+b,0)/x.deliveryDays.length:0})).sort((a,b)=>new Date(a.sortDate)-new Date(b.sortDate))}
 return{detailedReturns,returnsByCustomer,returnsByProduct,returnsByRep,returnValue,deliveryRows,pendingDelivery,deliveredOrders,deliveryByCustomer:groupDelivery('customerId','customer',true),deliveryByRep:groupDelivery('repId','salesRep'),deliveryPerformance,invoiceRows,invoiceSalesTotal}
}
export const reportMath={number:n,sum:total,daysBetween:days}
