-- Sales foundation and historical cost support.
-- Safe to run repeatedly. Existing tables and rows are preserved.

create extension if not exists pgcrypto;

-- This project snapshot may have inventory tables without the sales tables.
-- Create the minimum employee and sales schema expected by the application.
create table if not exists public.employees (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text,
  phone1 text,
  is_rep boolean not null default true,
  commission_rate numeric(7,4),
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number bigint generated by default as identity unique,
  customer_id uuid references public.customers(id) on delete restrict,
  rep_id uuid references public.employees(id) on delete set null,
  total_amount numeric(14,2) not null default 0,
  vat_rate numeric(7,4) not null default 0,
  vat_amount numeric(14,2) not null default 0,
  payment_type text not null default 'credit'
    check (payment_type in ('cash', 'credit')),
  created_at timestamptz not null default now()
);

create table if not exists public.invoice_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  variant_id uuid references public.product_variants(id) on delete restrict,
  product_id uuid references public.products(id) on delete restrict,
  quantity numeric(14,3) not null check (quantity > 0),
  price numeric(14,2) not null default 0,
  discount numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  cost_price numeric(14,2),
  created_at timestamptz not null default now(),
  constraint invoice_items_product_reference check (variant_id is not null or product_id is not null)
);

-- Also upgrades an existing product-level invoice_items table without removing
-- its product_id. New variant-aware sales should populate variant_id.
alter table public.invoice_items add column if not exists variant_id uuid;
alter table public.invoice_items add column if not exists product_id uuid;
do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'invoice_items_variant_id_fkey'
      and conrelid = 'public.invoice_items'::regclass
  ) then
    alter table public.invoice_items add constraint invoice_items_variant_id_fkey
      foreign key (variant_id) references public.product_variants(id) on delete restrict;
  end if;
end $$;

create table if not exists public.invoice_payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  amount numeric(14,2) not null check (amount > 0),
  paid_at date not null default current_date,
  method text not null default 'cash',
  bank_name text,
  reference text,
  note text,
  created_at timestamptz not null default now()
);

alter table public.invoice_items
  add column if not exists cost_price numeric(14,2);

comment on column public.invoice_items.cost_price is
  'Immutable unit cost captured when the invoice line is created. Never replace with current product cost.';

-- Backfill legacy lines with the most recent purchase cost that existed on the
-- invoice date. Lines without any prior purchase remain NULL (shown as uncosted).
update public.invoice_items ii
set cost_price = (
  select pi.cost_price
  from public.purchase_items pi
  join public.purchases p on p.id = pi.purchase_id
  join public.invoices i on i.id = ii.invoice_id
  left join public.product_variants pv on pv.id = pi.variant_id
  where (
    pi.variant_id = ii.variant_id
    or (ii.variant_id is null and pv.product_id = ii.product_id)
  )
    and p.purchase_date <= i.created_at
  order by p.purchase_date desc, pi.created_at desc, pi.id desc
  limit 1
)
where ii.cost_price is null
  and exists (
    select 1
    from public.purchase_items pi
    join public.purchases p on p.id = pi.purchase_id
    join public.invoices i on i.id = ii.invoice_id
    left join public.product_variants pv on pv.id = pi.variant_id
    where (
      pi.variant_id = ii.variant_id
      or (ii.variant_id is null and pv.product_id = ii.product_id)
    )
      and p.purchase_date <= i.created_at
  );

create index if not exists invoices_sales_report_date_idx
  on public.invoices (created_at desc);
create index if not exists invoices_sales_report_dimensions_idx
  on public.invoices (customer_id, rep_id, payment_type, created_at desc);
create index if not exists invoice_items_sales_report_idx
  on public.invoice_items (invoice_id, variant_id, product_id);
create index if not exists invoice_payments_report_idx
  on public.invoice_payments (invoice_id, paid_at);
create index if not exists purchase_items_product_report_idx
  on public.purchase_items (variant_id, purchase_id);

-- Ask PostgREST to refresh relationships after this migration.
notify pgrst, 'reload schema';
