-- Sales foundation and historical cost support.
-- Safe to run repeatedly. Existing tables and rows are preserved.

create extension if not exists pgcrypto;

-- Ensure employees table exists
create table if not exists public.employees (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text,
  phone1 text,
  is_rep boolean not null default true,
  commission_rate numeric(7,4),
  status text not null default 'active',
  created_at timestamptz not null default now()
);

-- Ensure invoices table exists
create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number bigint generated by default as identity unique,
  customer_id uuid references public.customers(id) on delete restrict,
  rep_id uuid references public.employees(id) on delete set null,
  total_amount numeric(14,2) not null default 0,
  vat_rate numeric(7,4) not null default 0,
  vat_amount numeric(14,2) not null default 0,
  payment_type text not null default 'credit' check (payment_type in ('cash', 'credit')),
  created_at timestamptz not null default now()
);

-- Ensure invoice_items table exists
create table if not exists public.invoice_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  product_id uuid references public.products(id) on delete restrict,
  quantity numeric(14,3) not null check (quantity > 0),
  price numeric(14,2) not null default 0,
  discount numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  cost_price numeric(14,2),
  created_at timestamptz not null default now()
);

-- Ensure invoice_payments table exists
create table if not exists public.invoice_payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  amount numeric(14,2) not null check (amount > 0),
  paid_at date not null default current_date,
  method text not null default 'cash',
  bank_name text,
  reference text,
  note text,
  created_at timestamptz not null default now()
);

-- Add status to invoices if not already present
alter table public.invoices add column if not exists status text not null default 'completed';

-- Add cost_price to invoice_items if not already present
alter table public.invoice_items add column if not exists cost_price numeric(14,2);

comment on column public.invoice_items.cost_price is
  'Immutable unit cost captured when the invoice line is created. Never replace with current product cost.';

-- Backfill existing lines with the most recent purchase cost on or before the invoice date
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'purchase_items' and column_name = 'cost'
  ) and exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'purchases' and column_name = 'date'
  ) then
    update public.invoice_items ii
    set cost_price = (
      select pi.cost
      from public.purchase_items pi
      join public.purchases p on p.id = pi.purchase_id
      join public.invoices i on i.id = ii.invoice_id
      where pi.product_id = ii.product_id
        and coalesce(p.date::timestamptz, p.created_at) <= i.created_at
        and coalesce(lower(p.status), 'completed') not in ('cancelled', 'canceled', 'draft', 'deleted', 'reversed', 'void')
      order by coalesce(p.date::timestamptz, p.created_at) desc, pi.id desc
      limit 1
    )
    where ii.cost_price is null;
  end if;
end $$;

-- Performance indexes
create index if not exists invoices_sales_report_date_idx
  on public.invoices (created_at desc);
create index if not exists invoices_sales_report_dimensions_idx
  on public.invoices (customer_id, rep_id, payment_type, created_at desc);
create index if not exists invoice_items_invoice_product_idx
  on public.invoice_items (invoice_id, product_id);
create index if not exists invoice_payments_report_idx
  on public.invoice_payments (invoice_id, paid_at);

-- Reload PostgREST schema cache
notify pgrst, 'reload schema';
