import React from 'react';
import { Link } from 'react-router-dom';
import { FileText, Download, Printer, ArrowLeft } from 'lucide-react';
import html2pdf from 'html2pdf.js';
import * as XLSX from 'xlsx';

export function ReportHeader({ title, subtitle, generatedBy, generatedDate }) {
  return (
    <div className="mb-4 rounded-lg border border-slate-200 bg-white p-4 dark:border-emerald-400/20 dark:bg-emerald-950/25">
      <div className="flex flex-col justify-between gap-3 md:flex-row md:items-center">
        <div className="flex items-center gap-3">
          <Link
            to="/reports"
            className="rounded-md border border-slate-300 p-1.5 text-slate-700 transition-colors hover:bg-slate-50 dark:border-emerald-400/20 dark:text-emerald-50 dark:hover:bg-emerald-500/10"
          >
            <ArrowLeft size={20} />
          </Link>
          <div>
            <h1 className="text-xl font-bold text-slate-900 dark:text-white">{title}</h1>
            {subtitle && <p className="mt-0.5 text-sm text-slate-500 dark:text-emerald-100/70">{subtitle}</p>}
          </div>
        </div>
        <div className="text-sm text-slate-600 dark:text-emerald-100/70">
          <p><span className="font-medium">Generated by:</span> {generatedBy}</p>
          <p><span className="font-medium">Generated on:</span> {generatedDate}</p>
        </div>
      </div>
    </div>
  );
}

export function SummaryCards({ cards }) {
  return (
    <div className="mb-4 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5">
      {cards.map((card, idx) => (
        <div
          key={idx}
          className="rounded-lg border border-slate-200 bg-white p-3 dark:border-emerald-400/20 dark:bg-emerald-950/25"
        >
          <p className="mb-1 text-[11px] font-semibold uppercase tracking-wide text-slate-500 dark:text-emerald-100/60">{card.label}</p>
          <p className="text-base font-bold tabular-nums text-slate-900 dark:text-white">{card.value}</p>
        </div>
      ))}
    </div>
  );
}

export function ReportActions({ onPrint, onExportPDF, onExportExcel, children }) {
  return (
    <div className="mb-4 flex flex-wrap items-center gap-2 print:hidden">
      {children}
      <div className="ml-auto flex flex-wrap items-center gap-2">
        <button
          onClick={onPrint}
          className="flex items-center gap-2 rounded-md border border-slate-300 px-3 py-1.5 text-sm font-medium text-slate-700 transition-colors hover:bg-slate-50 dark:border-emerald-400/20 dark:text-emerald-50 dark:hover:bg-emerald-500/10"
        >
          <Printer size={16} />
          Print
        </button>
        <button
          onClick={onExportPDF}
          className="flex items-center gap-2 rounded-md border border-slate-300 px-3 py-1.5 text-sm font-medium text-slate-700 transition-colors hover:bg-slate-50 dark:border-emerald-400/20 dark:text-emerald-50 dark:hover:bg-emerald-500/10"
        >
          <FileText size={16} />
          Download PDF
        </button>
        <button
          onClick={onExportExcel}
          className="flex items-center gap-2 rounded-md bg-emerald-600 px-3 py-1.5 text-sm font-medium text-white transition-colors hover:bg-emerald-700"
        >
          <Download size={16} />
          Export Excel
        </button>
      </div>
    </div>
  );
}

export function ReportPagination({ page, setPage, totalPages, pageSize, setPageSize, total }) {
  return (
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-200 bg-white p-3 dark:border-emerald-400/20 dark:bg-emerald-950/25 print:hidden">
      <p className="text-sm text-slate-600 dark:text-emerald-100/70">
        Showing <span className="font-medium">{((page - 1) * pageSize) + 1}</span> to <span className="font-medium">{Math.min(page * pageSize, total)}</span> of <span className="font-medium">{total}</span>
      </p>
      <div className="flex items-center gap-3">
        <div className="flex items-center gap-2">
          <span className="text-sm text-slate-600 dark:text-emerald-100/70">Per page:</span>
          <select
            value={pageSize}
            onChange={(e) => {
              setPageSize(Number(e.target.value));
              setPage(1);
            }}
            className="rounded-lg border border-slate-300 dark:border-emerald-400/20 bg-white dark:bg-slate-900 px-3 py-2 text-sm text-slate-700 dark:text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/20"
          >
            <option value={5}>5</option>
            <option value={10}>10</option>
            <option value={25}>25</option>
            <option value={50}>50</option>
          </select>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setPage(Math.max(1, page - 1))}
            disabled={page === 1}
            className="px-3 py-1.5 rounded-lg border border-slate-300 dark:border-emerald-400/20 text-sm font-medium text-slate-700 dark:text-emerald-50 hover:bg-slate-50 dark:hover:bg-emerald-500/10 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            Previous
          </button>
          <span className="text-sm font-medium text-slate-900 dark:text-white">
            {page} / {totalPages}
          </span>
          <button
            onClick={() => setPage(Math.min(totalPages, page + 1))}
            disabled={page === totalPages}
            className="px-3 py-1.5 rounded-lg border border-slate-300 dark:border-emerald-400/20 text-sm font-medium text-slate-700 dark:text-emerald-50 hover:bg-slate-50 dark:hover:bg-emerald-500/10 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            Next
          </button>
        </div>
      </div>
    </div>
  );
}

export function LoadingSkeleton() {
  return (
    <div className="space-y-6">
      <div className="bg-white dark:bg-emerald-950/25 border border-slate-200 dark:border-emerald-400/20 rounded-xl p-6 shadow-sm animate-pulse">
        <div className="h-8 bg-slate-200 dark:bg-emerald-900/40 rounded w-64"></div>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4">
        {[...Array(6)].map((_, i) => (
          <div key={i} className="bg-white dark:bg-emerald-950/25 border border-slate-200 dark:border-emerald-400/20 rounded-xl p-5 shadow-sm animate-pulse">
            <div className="h-4 bg-slate-200 dark:bg-emerald-900/40 rounded w-32 mb-2"></div>
            <div className="h-8 bg-slate-200 dark:bg-emerald-900/40 rounded"></div>
          </div>
        ))}
      </div>
      <div className="bg-white dark:bg-emerald-950/25 border border-slate-200 dark:border-emerald-400/20 rounded-xl overflow-hidden shadow-sm animate-pulse">
        <div className="p-5 border-b border-slate-200 dark:border-emerald-400/20">
          <div className="h-4 bg-slate-200 dark:bg-emerald-900/40 rounded w-48"></div>
        </div>
        <div className="p-5">
          {[...Array(5)].map((_, i) => (
            <div key={i} className="h-12 bg-slate-200 dark:bg-emerald-900/40 rounded mb-3"></div>
          ))}
        </div>
      </div>
    </div>
  );
}

export function EmptyState({ message }) {
  return (
    <div className="bg-white dark:bg-emerald-950/25 border border-slate-200 dark:border-emerald-400/20 rounded-xl p-12 text-center shadow-sm">
      <p className="text-lg text-slate-500 dark:text-emerald-100/70">{message}</p>
    </div>
  );
}

// Helper functions for export
export function exportToExcel(data, filename = 'report.xlsx', sheetName = 'Report') {
  const ws = XLSX.utils.json_to_sheet(data);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName);
  XLSX.writeFile(wb, filename);
}

export function exportToPDF(elementId, filename = 'report.pdf', options = {}) {
  const element = document.getElementById(elementId);
  if (!element) return;

  const cloned = element.cloneNode(true);
  cloned.classList.add('pdf-export-document');
  if (options.className) cloned.classList.add(options.className);

  const wrapper = document.createElement('div');
  wrapper.className = 'pdf-export-stage';
  wrapper.appendChild(cloned);
  document.body.appendChild(wrapper);

  const orientation = options.orientation ?? (element.scrollWidth > 900 ? 'landscape' : 'portrait');
  const format = options.format ?? 'a4';
  const opt = {
    margin: options.margin ?? 0.25,
    filename: filename,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: {
      scale: options.scale ?? 2,
      useCORS: true,
      backgroundColor: '#ffffff',
      scrollX: 0,
      scrollY: 0,
      windowWidth: cloned.scrollWidth,
    },
    jsPDF: { unit: 'in', format, orientation },
    pagebreak: { mode: ['css', 'legacy'], avoid: ['tr', '.pdf-avoid-break'] },
  };
  const worker = html2pdf().set(opt).from(cloned);
  const save = options.pageNumbers
    ? worker.toPdf().get('pdf').then((pdf) => {
        const pages = pdf.internal.getNumberOfPages();
        for (let page = 1; page <= pages; page += 1) {
          pdf.setPage(page);
          pdf.setFontSize(8);
          pdf.setTextColor(100);
          pdf.text(`Page ${page} of ${pages}`, pdf.internal.pageSize.getWidth() - 0.65, pdf.internal.pageSize.getHeight() - 0.2, { align: 'right' });
        }
      }).save()
    : worker.save();
  save.finally(() => {
    document.body.removeChild(wrapper);
  });
}
