import React, { useEffect, useMemo, useState } from 'react'
import { Check, ChevronDown, Download, FileSpreadsheet, Filter, Printer, RefreshCw, Search, Settings2 } from 'lucide-react'
import * as XLSX from 'xlsx'
import { supabase } from '../../lib/supabaseClient'
import { useAuth } from '../../contexts/AuthContext'
import { usePermissions } from '../../contexts/PermissionsContext'
import { useToast } from '../../contexts/ToastContext'
import logo from '../../pictures/logo.jpeg'
import { exportToPDF, LoadingSkeleton } from '../../components/reports'
import { bankWiseRows, buildChequeRegister, CHEQUE_REPORTS, chequeDashboard, REPORT_COLUMNS, rowsForReport, summaryForReport } from '../../lib/chequeReports'

const TABLES = ['customer_cheques', 'invoice_payments', 'purchase_payments', 'invoices', 'purchases', 'customers', 'vendors', 'banks', 'bank_reconciliation_items', 'returns', 'audit_logs']
const MONEY = new Intl.NumberFormat('en-LK', { style: 'currency', currency: 'LKR', minimumFractionDigits: 2 })
const money = (value) => MONEY.format(Number(value ?? 0))
const formatDate = (value) => value ? new Date(`${String(value).slice(0, 10)}T00:00:00`).toLocaleDateString() : '-'
const localDay = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const inputClass = 'w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none focus:border-emerald-500 dark:border-emerald-400/20 dark:bg-slate-950 dark:text-white'

function presetDates(preset) {
  if (preset === 'all') return { from: '', to: '' }
  const now = new Date(), start = new Date(now.getFullYear(), now.getMonth(), now.getDate()), end = new Date(start)
  if (preset === 'yesterday') { start.setDate(start.getDate() - 1); end.setDate(end.getDate() - 1) }
  if (preset === 'this-week') start.setDate(start.getDate() - ((start.getDay() + 6) % 7))
  if (preset === 'this-month') start.setDate(1)
  if (preset === 'last-month') { start.setMonth(start.getMonth() - 1, 1); end.setDate(0) }
  return { from: localDay(start), to: localDay(end) }
}

const emptyFilters = () => ({ preset: 'all', from: '', to: '', customerId: '', vendorId: '', bank: '', depositBankId: '', status: '', type: '', chequeNumber: '', minAmount: '', maxAmount: '' })

function FilterField({ label, children }) {
  return <label className="block"><span className="mb-1 block text-[11px] font-bold uppercase tracking-wide text-slate-500 dark:text-emerald-100/60">{label}</span>{children}</label>
}

function SummaryCards({ items }) {
  return <div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-6">
    {items.map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-emerald-400/20 dark:bg-emerald-950/30">
      <div className="text-[11px] font-bold uppercase tracking-wide text-slate-500 dark:text-emerald-100/60">{label}</div>
      <div className="mt-1 text-lg font-extrabold text-slate-900 dark:text-white">{typeof value === 'number' && (/value|amount|largest|reconciled/i.test(label) || ['In Hand', 'Deposited', 'Cleared', 'Returned', 'Pending'].includes(label)) ? money(value) : Number(value ?? 0).toLocaleString()}</div>
    </div>)}
  </div>
}

function PrintDocument({ report, columns, rows, summary, filters, generatedBy }) {
  const applied = [filters.customerId && 'Customer selected', filters.vendorId && 'Vendor selected', filters.bank && `Bank: ${filters.bank}`, filters.depositBankId && 'Deposit bank selected', filters.status && `Status: ${filters.status}`, filters.type && `Type: ${filters.type}`, filters.chequeNumber && `Cheque: ${filters.chequeNumber}`].filter(Boolean).join(' " ') || 'No additional filters'
  return <div id="cheque-report-print" className="bg-white p-6 text-slate-900">
    <header className="mb-5 flex items-center justify-between border-b-2 border-emerald-700 pb-4">
      <div className="flex items-center gap-4"><img src={logo} className="h-16 w-16 rounded object-cover" alt="Company logo"/><div><div className="text-2xl font-black">Shayan's Kids & Toys Store</div><div className="text-sm">Wholesale Management System " Sri Lanka</div></div></div>
      <div className="text-right"><div className="text-xl font-black text-emerald-800">{report.title}</div><div className="text-xs">{filters.from || 'All dates'}  {filters.to || 'Present'}</div></div>
    </header>
    <div className="mb-4 grid grid-cols-2 gap-2 text-xs"><div><b>Applied filters:</b> {applied}</div><div className="text-right"><b>Generated by:</b> {generatedBy}<br/><b>Generated:</b> {new Date().toLocaleString()}</div></div>
    <div className="mb-4 grid grid-cols-4 gap-2">{summary.map(([label, value]) => <div key={label} className="border border-slate-300 p-2"><div className="text-[9px] uppercase text-slate-500">{label}</div><div className="font-bold">{typeof value === 'number' ? value.toLocaleString() : value}</div></div>)}</div>
    <table className="w-full border-collapse text-[8px]"><thead><tr>{columns.map(([column, heading]) => <th key={column} className="border border-slate-300 bg-slate-100 p-1 text-left">{heading}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.id ?? index}>{columns.map(([column, , type]) => <td key={column} className="border border-slate-200 p-1">{type === 'money' ? money(row[column]) : type === 'date' ? formatDate(row[column]) : String(row[column] ?? '-')}</td>)}</tr>)}</tbody></table>
    <footer className="mt-4 border-t pt-2 text-center text-[10px] text-slate-500">Live cheque records " Shayan's Kids Cheque Reports</footer>
  </div>
}

function MiniTable({ title, rows }) {
  return <div className="overflow-hidden rounded-xl border border-slate-200 bg-white text-slate-800 dark:border-emerald-400/20 dark:bg-emerald-950/30 dark:text-emerald-50">
    <div className="border-b border-slate-200 px-4 py-3 text-sm font-bold text-slate-800 dark:border-emerald-400/20 dark:text-white">{title}</div>
    <div className="overflow-auto"><table className="w-full min-w-[560px] text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500 dark:bg-emerald-950/50 dark:text-emerald-100/60"><tr><th className="p-3 text-left">Party</th><th className="p-3 text-left">Cheque</th><th className="p-3 text-left">Date</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id} className="border-t border-slate-100 dark:border-emerald-400/10"><td className="p-3">{row.party}</td><td className="p-3">{row.chequeNumber}</td><td className="p-3">{formatDate(row.chequeDate)}</td><td className="p-3 text-right font-semibold">{money(row.amount)}</td></tr>) : <tr><td colSpan={4} className="p-5 text-center text-slate-500">No records</td></tr>}</tbody></table></div>
  </div>
}

export default function ChequeReportsPage({ initialMode = 'summary' }) {
  const toast = useToast()
  const { user } = useAuth()
  const { can, isSuperAdmin, record } = usePermissions()
  const canPrint = isSuperAdmin || can('reports_cheques', 'print')
  const canExport = isSuperAdmin || can('reports_cheques', 'export')
  const [active, setActive] = useState(initialMode)
  const [raw, setRaw] = useState(null)
  const [warnings, setWarnings] = useState([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [draftFilters, setDraftFilters] = useState(emptyFilters)
  const [filters, setFilters] = useState(emptyFilters)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(25)
  const [sort, setSort] = useState({ key: 'transactionDate', direction: 'desc' })
  const [visible, setVisible] = useState({})
  const [showColumns, setShowColumns] = useState(false)

  const load = async () => {
    setLoading(true)
    const results = await Promise.all(TABLES.map(async (table) => ({ table, ...(await supabase.from(table).select('*')) })))
    const next = {}, failed = []
    results.forEach(({ table, data, error }) => { next[table] = data ?? []; if (error) failed.push(`${table}: ${error.message}`) })
    setRaw(next); setWarnings(failed); setLoading(false)
  }
  useEffect(() => { load().catch((error) => { toast.error(error.message ?? 'Failed to load cheque reports'); setLoading(false) }) }, [])

  const register = useMemo(() => raw ? buildChequeRegister(raw) : [], [raw])
  const filteredRegister = useMemo(() => register.filter((row) => {
    const date = row.transactionDate || row.chequeDate
    const amount = Number(row.amount ?? 0)
    return (!filters.from || !date || date >= filters.from) && (!filters.to || !date || date <= filters.to) &&
      (!filters.customerId || String(row.customerId) === String(filters.customerId)) && (!filters.vendorId || String(row.vendorId) === String(filters.vendorId)) &&
      (!filters.bank || row.bankName === filters.bank) && (!filters.depositBankId || String(row.depositBankId) === String(filters.depositBankId)) &&
      (!filters.status || row.status === filters.status) && (!filters.type || row.type === filters.type) &&
      (!filters.chequeNumber || String(row.chequeNumber).toLowerCase().includes(filters.chequeNumber.toLowerCase())) &&
      (filters.minAmount === '' || amount >= Number(filters.minAmount)) && (filters.maxAmount === '' || amount <= Number(filters.maxAmount))
  }), [register, filters])
  const report = CHEQUE_REPORTS.find((item) => item.key === active) ?? CHEQUE_REPORTS[0]
  const baseRows = useMemo(() => active === 'bank-wise' ? bankWiseRows(filteredRegister) : rowsForReport(filteredRegister, active, filters), [filteredRegister, active, filters])
  const searchedRows = useMemo(() => {
    const q = search.trim().toLowerCase()
    const result = q ? baseRows.filter((row) => Object.values(row).some((value) => String(value ?? '').toLowerCase().includes(q))) : baseRows
    return [...result].sort((a, b) => {
      const left = a[sort.key] ?? '', right = b[sort.key] ?? ''
      const compared = typeof left === 'number' && typeof right === 'number' ? left - right : String(left).localeCompare(String(right))
      return sort.direction === 'asc' ? compared : -compared
    })
  }, [baseRows, search, sort])
  const columns = REPORT_COLUMNS[active] ?? REPORT_COLUMNS.register
  const shownColumns = columns.filter(([column]) => visible[column] !== false)
  const totalPages = Math.max(1, Math.ceil(searchedRows.length / pageSize))
  const pagedRows = searchedRows.slice((Math.min(page, totalPages) - 1) * pageSize, Math.min(page, totalPages) * pageSize)
  const summary = active === 'summary' ? chequeDashboard(filteredRegister) : active === 'bank-wise' ? [['Banks', searchedRows.length], ['Cheques', searchedRows.reduce((sum, row) => sum + row.count, 0)], ['Total Value', searchedRows.reduce((sum, row) => sum + row.totalAmount, 0)]] : summaryForReport(searchedRows, active)
  const generatedBy = record?.display_name || user?.email || 'System User'

  useEffect(() => { setPage(1); setVisible({}); setSort({ key: active === 'bank-wise' ? 'totalAmount' : 'transactionDate', direction: 'desc' }) }, [active])

  const exportRows = () => searchedRows.map((row) => Object.fromEntries(shownColumns.map(([column, heading, type]) => [heading, type === 'date' ? formatDate(row[column]) : row[column] ?? '-'])))
  const exportExcel = () => { const ws = XLSX.utils.json_to_sheet(exportRows()), wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'Cheque Report'); XLSX.writeFile(wb, `${active}-cheque-report.xlsx`) }
  const exportCsv = () => { const csv = XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(exportRows())); const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${active}-cheque-report.csv`; link.click(); URL.revokeObjectURL(link.href) }
  const print = () => { const html = document.getElementById('cheque-report-print')?.outerHTML; if (!html) return; const win = window.open('', '_blank'); win.document.write(`<html><head><title>${report.title}</title><style>@page{size:A4 landscape;margin:10mm}body{font-family:Arial;color:#0f172a}table{width:100%;border-collapse:collapse}th,td{border:1px solid #cbd5e1;padding:4px;font-size:9px}img{width:60px}</style></head><body>${html}</body></html>`); win.document.close(); win.print() }

  if (loading) return <LoadingSkeleton />
  return <div className="space-y-5 text-slate-800 dark:text-emerald-50">
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-emerald-400/20 dark:bg-emerald-950/30">
      <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><h1 className="text-2xl font-black text-slate-900 dark:text-white">Cheque Reports</h1><p className="mt-1 text-sm text-slate-500 dark:text-emerald-100/70">Live customer, vendor, deposit, clearance, return and due-cheque reporting.</p></div>
        <div className="flex flex-wrap gap-2">
          {canPrint && <><button onClick={print} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold dark:border-emerald-400/20"><Printer size={16}/> Print</button><button onClick={() => exportToPDF('cheque-report-print', `${active}-cheque-report.pdf`, { orientation: 'landscape', pageNumbers: true })} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold dark:border-emerald-400/20"><Download size={16}/> PDF</button></>}
          {canExport && <><button onClick={exportExcel} className="flex items-center gap-2 rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white"><FileSpreadsheet size={16}/> Excel</button><button onClick={exportCsv} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold dark:border-emerald-400/20">CSV</button></>}
        </div>
      </div>
    </div>
    {warnings.length > 0 && <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800 dark:border-amber-800/40 dark:bg-amber-950/30 dark:text-amber-200">Some optional data could not be loaded: {warnings.join(' " ')}</div>}
    <div className="flex gap-2 overflow-x-auto pb-1">{CHEQUE_REPORTS.map((item) => <button key={item.key} onClick={() => setActive(item.key)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold ${active === item.key ? 'bg-emerald-600 text-white' : 'border border-slate-200 bg-white text-slate-700 dark:border-emerald-400/20 dark:bg-emerald-950/30 dark:text-emerald-50'}`}>{item.title.replace(' Report', '')}</button>)}</div>

    <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-emerald-400/20 dark:bg-emerald-950/30">
      <div className="mb-3 flex items-center gap-2 text-sm font-bold text-slate-800 dark:text-white"><Filter size={16}/> Filters</div>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-6">
        <FilterField label="Date period"><select className={inputClass} value={draftFilters.preset} onChange={(event) => { const preset = event.target.value; setDraftFilters((old) => ({ ...old, preset, ...presetDates(preset) })) }}><option value="all">All Dates</option><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="this-week">This Week</option><option value="this-month">This Month</option><option value="last-month">Last Month</option><option value="custom">Custom Range</option></select></FilterField>
        <FilterField label="From"><input type="date" className={inputClass} value={draftFilters.from} onChange={(event) => setDraftFilters((old) => ({ ...old, preset: 'custom', from: event.target.value }))}/></FilterField>
        <FilterField label="To"><input type="date" className={inputClass} value={draftFilters.to} onChange={(event) => setDraftFilters((old) => ({ ...old, preset: 'custom', to: event.target.value }))}/></FilterField>
        <FilterField label="Customer"><select className={inputClass} value={draftFilters.customerId} onChange={(event) => setDraftFilters((old) => ({ ...old, customerId: event.target.value }))}><option value="">All Customers</option>{(raw?.customers ?? []).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></FilterField>
        <FilterField label="Vendor"><select className={inputClass} value={draftFilters.vendorId} onChange={(event) => setDraftFilters((old) => ({ ...old, vendorId: event.target.value }))}><option value="">All Vendors</option>{(raw?.vendors ?? []).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></FilterField>
        <FilterField label="Originating Bank"><select className={inputClass} value={draftFilters.bank} onChange={(event) => setDraftFilters((old) => ({ ...old, bank: event.target.value }))}><option value="">All Banks</option>{[...new Set(register.map((row) => row.bankName).filter(Boolean))].sort().map((name) => <option key={name}>{name}</option>)}</select></FilterField>
        <FilterField label="Deposit Bank"><select className={inputClass} value={draftFilters.depositBankId} onChange={(event) => setDraftFilters((old) => ({ ...old, depositBankId: event.target.value }))}><option value="">All Deposit Banks</option>{(raw?.banks ?? []).map((row) => <option key={row.id} value={row.id}>{row.code ? `${row.code} - ` : ''}{row.name}</option>)}</select></FilterField>
        <FilterField label="Cheque Status"><select className={inputClass} value={draftFilters.status} onChange={(event) => setDraftFilters((old) => ({ ...old, status: event.target.value }))}><option value="">All Statuses</option>{[...new Set(register.map((row) => row.status).filter(Boolean))].sort().map((status) => <option key={status} value={status}>{status.replaceAll('_', ' ')}</option>)}</select></FilterField>
        <FilterField label="Cheque Type"><select className={inputClass} value={draftFilters.type} onChange={(event) => setDraftFilters((old) => ({ ...old, type: event.target.value }))}><option value="">All Types</option><option>Customer</option><option>Vendor</option></select></FilterField>
        <FilterField label="Cheque Number"><input className={inputClass} value={draftFilters.chequeNumber} onChange={(event) => setDraftFilters((old) => ({ ...old, chequeNumber: event.target.value }))} placeholder="Cheque number"/></FilterField>
        <FilterField label="Minimum Amount"><input type="number" min="0" className={inputClass} value={draftFilters.minAmount} onChange={(event) => setDraftFilters((old) => ({ ...old, minAmount: event.target.value }))}/></FilterField>
        <FilterField label="Maximum Amount"><input type="number" min="0" className={inputClass} value={draftFilters.maxAmount} onChange={(event) => setDraftFilters((old) => ({ ...old, maxAmount: event.target.value }))}/></FilterField>
      </div>
      <div className="mt-3 flex flex-wrap gap-2"><button onClick={() => { setFilters(draftFilters); setPage(1) }} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Apply Filters</button><button onClick={() => { const blank = emptyFilters(); setDraftFilters(blank); setFilters(blank); setSearch(''); setPage(1) }} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold dark:border-emerald-400/20">Reset Filters</button><button onClick={load} className="flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold dark:border-emerald-400/20"><RefreshCw size={15}/> Refresh</button></div>
    </div>

    <div><div className="text-lg font-black text-slate-900 dark:text-white">{report.title}</div><div className="text-sm text-slate-500 dark:text-emerald-100/70">{report.description}</div></div>
    <SummaryCards items={summary}/>

    {active === 'summary' ? <div className="grid gap-4 xl:grid-cols-3">
      <MiniTable title="Latest Cheques In Hand" rows={filteredRegister.filter((row) => row.status === 'in_hand').sort((a, b) => String(b.transactionDate).localeCompare(String(a.transactionDate))).slice(0, 5)}/>
      <MiniTable title="Latest Deposits" rows={filteredRegister.filter((row) => row.status === 'deposited').sort((a, b) => String(b.depositDate).localeCompare(String(a.depositDate))).slice(0, 5)}/>
      <MiniTable title="Latest Returned Cheques" rows={filteredRegister.filter((row) => row.status === 'returned').sort((a, b) => String(b.returnedDate).localeCompare(String(a.returnedDate))).slice(0, 5)}/>
    </div> : <>
      <div className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-3 dark:border-emerald-400/20 dark:bg-emerald-950/30 md:flex-row md:items-center">
        <div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className={`${inputClass} pl-9`} value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} placeholder="Search all visible report data"/></div>
        <div className="relative"><button onClick={() => setShowColumns((value) => !value)} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold dark:border-emerald-400/20"><Settings2 size={16}/> Columns <ChevronDown size={14}/></button>{showColumns && <div className="absolute right-0 z-20 mt-2 max-h-80 w-64 overflow-auto rounded-xl border border-slate-200 bg-white p-2 shadow-xl dark:border-emerald-400/20 dark:bg-slate-950">{columns.map(([column, heading]) => <label key={column} className="flex items-center gap-2 rounded px-2 py-1.5 text-sm"><input type="checkbox" checked={visible[column] !== false} onChange={(event) => setVisible((old) => ({ ...old, [column]: event.target.checked }))}/><Check size={13} className={visible[column] !== false ? 'text-emerald-600' : 'invisible'}/>{heading}</label>)}</div>}</div>
      </div>
      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-emerald-400/20 dark:bg-emerald-950/30">
        <div className="overflow-auto"><table className="w-full min-w-max text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500 dark:bg-emerald-950/60 dark:text-emerald-100/60"><tr>{shownColumns.map(([column, heading]) => <th key={column} onClick={() => setSort((old) => ({ key: column, direction: old.key === column && old.direction === 'asc' ? 'desc' : 'asc' }))} className="cursor-pointer whitespace-nowrap p-3 text-left">{heading}{sort.key === column ? (sort.direction === 'asc' ? ' ASC' : ' DESC') : ''}</th>)}</tr></thead><tbody>{pagedRows.length ? pagedRows.map((row) => <tr key={row.id} className="border-t border-slate-100 hover:bg-slate-50 dark:border-emerald-400/10 dark:hover:bg-emerald-500/5">{shownColumns.map(([column, , type]) => <td key={column} className={`whitespace-nowrap p-3 ${type === 'money' ? 'text-right font-semibold' : ''}`}>{active === 'bank-wise' && column === 'bankName' ? <button className="font-semibold text-emerald-700 underline" onClick={() => { const next = { ...filters, bank: row.bankName }; setFilters(next); setDraftFilters(next); setActive('register') }}>{row.bankName}</button> : type === 'money' ? money(row[column]) : type === 'date' ? formatDate(row[column]) : column === 'daysUntilDue' ? (row[column] < 0 ? `${Math.abs(row[column])} days overdue` : `${row[column]} days`) : String(row[column] ?? '-')}</td>)}</tr>) : <tr><td colSpan={shownColumns.length} className="p-10 text-center text-slate-500">No cheque records match the current report and filters.</td></tr>}</tbody></table></div>
      </div>
      <div className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-3 dark:border-emerald-400/20 dark:bg-emerald-950/30 sm:flex-row sm:items-center sm:justify-between"><div className="text-sm text-slate-500">Showing {searchedRows.length ? (page - 1) * pageSize + 1 : 0}-{Math.min(page * pageSize, searchedRows.length)} of {searchedRows.length}</div><div className="flex items-center gap-2"><select className={inputClass} value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1) }}><option value="10">10 rows</option><option value="25">25 rows</option><option value="50">50 rows</option><option value="100">100 rows</option></select><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm disabled:opacity-40 dark:border-emerald-400/20">Previous</button><span className="whitespace-nowrap text-sm">{Math.min(page, totalPages)} / {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm disabled:opacity-40 dark:border-emerald-400/20">Next</button></div></div>
    </>}
    <div className="fixed -left-[10000px] top-0 w-[1400px]"><PrintDocument report={report} columns={shownColumns} rows={searchedRows} summary={summary} filters={filters} generatedBy={generatedBy}/></div>
  </div>
}
