import React,{useEffect,useMemo,useState} from 'react'
import {Download,FileText,Printer} from 'lucide-react'
import {useAuth} from '../../contexts/AuthContext'
import {usePermissions} from '../../contexts/PermissionsContext'
import {supabase} from '../../lib/supabaseClient'
import {ReportHeader,SummaryCards,ReportPagination,LoadingSkeleton,EmptyState,exportToExcel,exportToPDF} from '../../components/reports'
import {buildStatement} from '../../lib/customerReports'

const money=v=>`Rs. ${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`, iso=d=>d.toISOString().slice(0,10), day=v=>v?new Date(v).toLocaleDateString():'—'
export default function CustomerStatementPage(){const {user}=useAuth(),{can,isSuperAdmin}=usePermissions(),[raw,setRaw]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[customerId,setCustomerId]=useState(''),[from,setFrom]=useState(()=>iso(new Date(new Date().getFullYear(),new Date().getMonth(),1))),[to,setTo]=useState(()=>iso(new Date())),[page,setPage]=useState(1),[size,setSize]=useState(30)
 useEffect(()=>{(async()=>{setLoading(true);const [customers,invoices,payments,returns,cheques]=await Promise.all(['customers','invoices','invoice_payments','returns','customer_cheques'].map(t=>supabase.from(t).select('*'))),fail=[customers,invoices,payments,returns].find(x=>x.error);if(fail)setError(fail.error.message);else{const data={customers:customers.data||[],invoices:invoices.data||[],payments:payments.data||[],returns:returns.data||[],cheques:cheques.data||[]};setRaw(data);setCustomerId(data.customers[0]?.id||'')}setLoading(false)})()},[])
 const statement=useMemo(()=>raw&&customerId?buildStatement(raw,customerId,from,to):{rows:[],opening:0,debits:0,credits:0,closing:0},[raw,customerId,from,to]),customer=raw?.customers.find(x=>x.id===customerId),pages=Math.max(1,Math.ceil(statement.rows.length/size)),shown=statement.rows.slice((page-1)*size,page*size),exportRows=()=>statement.rows.map(x=>({Date:day(x.date),'Created Date and Time':x.created,Reference:x.reference,'Transaction Type':x.type,Description:x.description,Debit:x.debit,Credit:x.credit,'Running Balance':x.balance,'Payment Method':x.method,Status:x.status}))
 if(loading)return <LoadingSkeleton/>;if(!isSuperAdmin&&!can('reports_customers','view'))return <div className="rounded-xl bg-rose-50 p-6 text-rose-700">Customer Reports permission is required.</div>
 return <div id="customer-statement" className="space-y-5"><ReportHeader title="Customer Statement" generatedBy={user?.email} generatedDate={new Date().toLocaleString()}/><section className="rounded-xl border bg-white p-4 dark:border-emerald-800 dark:bg-[#062a24] print:hidden"><div className="grid gap-3 md:grid-cols-3"><select className="field" value={customerId} onChange={e=>{setCustomerId(e.target.value);setPage(1)}}>{raw.customers.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><input className="field" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/><input className="field" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></div></section>{error&&<div className="rounded-xl bg-rose-50 p-4 text-rose-700">{error}</div>}
 {customer&&<section className="rounded-xl border bg-white p-5 dark:border-emerald-800 dark:bg-[#062a24]"><h2 className="text-xl font-bold">{customer.code} · {customer.name}</h2><p className="text-sm text-slate-500">{customer.address||'—'} · {customer.phone||'—'}</p><p className="mt-1 text-xs text-slate-500">Statement period: {from} through {to}</p></section>}
 <SummaryCards cards={[{label:'Opening Balance',value:money(statement.opening)},{label:'Total Invoices / Debits',value:money(statement.debits)},{label:'Payments & Credits',value:money(statement.credits)},{label:'Closing Balance',value:money(statement.closing)}]}/>
 <div className="flex gap-2 print:hidden"><button className="action" onClick={()=>window.print()}><Printer size={14}/>Print</button><button className="action" onClick={()=>exportToPDF('customer-statement','customer-statement.pdf',{orientation:'portrait'})}><FileText size={14}/>PDF</button><button className="action" onClick={()=>exportToExcel(exportRows(),'customer-statement.xlsx','Statement')}><Download size={14}/>Excel</button><button className="action" onClick={()=>{const data=exportRows(),csv=[Object.keys(data[0]||{}),...data.map(Object.values)].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv]));a.download='customer-statement.csv';a.click()}}><Download size={14}/>CSV</button></div>
 <div className="overflow-x-auto rounded-xl border bg-white dark:border-emerald-800 dark:bg-[#062a24]">{!shown.length?<EmptyState message="No customer transactions found for this period"/>:<table className="min-w-full text-sm"><thead><tr>{['Date','Reference','Transaction Type','Description','Debit','Credit','Running Balance','Payment Method','Status'].map(x=><th key={x} className="bg-slate-100 p-3 text-left dark:bg-emerald-900">{x}</th>)}</tr></thead><tbody>{shown.map((x,i)=><tr key={`${x.type}-${x.reference}-${i}`} className="border-t dark:border-emerald-900"><td className="p-3">{day(x.date)}</td><td className="p-3 font-semibold">{x.reference}</td><td className="p-3">{x.type}</td><td className="p-3">{x.description}</td><td className="p-3 text-right">{x.debit?money(x.debit):'—'}</td><td className="p-3 text-right">{x.credit?money(x.credit):'—'}</td><td className="p-3 text-right font-bold">{money(x.balance)}</td><td className="p-3">{x.method||'—'}</td><td className="p-3">{x.status}</td></tr>)}</tbody></table>}</div><ReportPagination page={page} setPage={setPage} totalPages={pages} pageSize={size} setPageSize={setSize} total={statement.rows.length}/></div>}
