import React, { useEffect, useMemo, useState } from 'react'
import * as XLSX from 'xlsx'
import { Download, FileText, Filter, Printer, RefreshCw, Search, SlidersHorizontal } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
import { useAuth } from '../../contexts/AuthContext'
import { usePermissions } from '../../contexts/PermissionsContext'
import { LoadingSkeleton, exportToPDF } from '../../components/reports'
import { buildRepReportModel, buildRepTransactions, day, inDateRange, num } from '../../lib/repReports'
import { REP_COLUMNS, REP_REPORTS, reportTitle } from './repReportConfig'
import logo from '../../pictures/logo.jpeg'

const money = (value) => `Rs. ${num(value).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const number = (value) => num(value).toLocaleString(undefined, { maximumFractionDigits: 2 })
const iso = (value) => value.toISOString().slice(0, 10)
const empty = { rep:'', customer:'', product:'', method:'', commissionStatus:'', paymentStatus:'', invoice:'', month:'', year:'', search:'' }
const valueAt = (row, key) => key.split('.').reduce((value, part) => value?.[part], row)
const display = (row, column) => { const value=valueAt(row,column.key); if(value==null||value==='')return '-'; if(column.type==='money')return money(value); if(column.type==='number')return number(value); if(column.type==='percent')return `${num(value).toFixed(2)}%`; if(column.type==='date')return new Date(value).toLocaleDateString(); if(column.type==='datetime')return new Date(value).toLocaleString(); return String(value) }
const rowDate = (mode, row) => ['monthly','settlement'].includes(mode) ? `${row.period}-01` : mode === 'advances' || mode === 'performance' || mode === 'customers' ? null : row.date

function preset(key) {
  const now=new Date(), today=new Date(now.getFullYear(),now.getMonth(),now.getDate()), to=new Date(today); let from=new Date(today)
  if(key==='yesterday'){from.setDate(from.getDate()-1);to.setDate(to.getDate()-1)}
  if(key==='week')from.setDate(from.getDate()-((from.getDay()+6)%7))
  if(key==='month')from=new Date(today.getFullYear(),today.getMonth(),1)
  if(key==='last'){from=new Date(today.getFullYear(),today.getMonth()-1,1);to.setDate(0)}
  if(key==='year')from=new Date(today.getFullYear(),0,1)
  return {from:iso(from),to:iso(to)}
}

function baseRows(mode, model) {
  if(mode==='sales')return model.salesRows
  if(mode==='monthly'||mode==='settlement')return model.periodRows
  if(mode==='payments')return model.paymentRows
  if(mode==='advances')return model.advanceRows
  if(mode==='customers')return model.customerRows
  if(mode==='collections')return model.collectionRows
  if(mode==='performance')return model.performanceRows
  return buildRepTransactions(model)
}

function summary(mode, rows, model) {
  const sum=(key)=>rows.reduce((total,row)=>total+num(row[key]),0)
  if(mode==='sales')return [['Total Orders',new Set(rows.map(x=>x.orderNumber).filter(x=>x&&x!=='-')).size],['Total Invoices',new Set(rows.map(x=>x.invoiceId)).size],['Quantity Sold',sum('quantity')],['Total Sales',money(sum('salesValue'))],['Gross Profit',money(sum('grossProfit'))],['Commission Earned',money(sum('commissionEarned'))]]
  if(mode==='monthly'||mode==='settlement'){const repIds=new Set(rows.map(x=>String(x.repId))),liveAdvance=(model?.advanceRows||[]).filter(x=>!repIds.size||repIds.has(String(x.repId))).reduce((s,x)=>s+num(x.currentAdvanceBalance),0);return [['Total Sales',money(sum('totalSales'))],['Commission Earned',money(sum('commissionEarned'))],['Amount Paid',money(sum('amountPaid'))],['Outstanding',money(sum('remainingDue'))],['Advance Balance',money(liveAdvance)]]}
  if(mode==='payments'){const periodDue=[...new Map(rows.map(x=>[String(x.repId)+'|'+x.period,x])).values()].reduce((s,x)=>s+num(x.remainingDue),0),repIds=new Set(rows.map(x=>String(x.repId))),advance=(model?.advanceRows||[]).filter(x=>!repIds.size||repIds.has(String(x.repId))).reduce((s,x)=>s+num(x.currentAdvanceBalance),0);return [['Total Payments',money(sum('amountPaid'))],['Commission Settled',money(sum('commissionSettled'))],['Advance Paid',money(sum('advanceCreated'))],['Outstanding',money(periodDue)],['Advance Balance',money(advance)]]}
  if(mode==='advances')return [['Commission Due',money(sum('currentCommissionDue'))],['Advance Balance',money(sum('currentAdvanceBalance'))],['Advance Created',money(sum('advanceCreated'))],['Advance Applied',money(sum('advanceApplied'))],['Net Payable',money(sum('netAmountPayable'))]]
  if(mode==='customers')return [['Rep / Customer Accounts',number(rows.length)],['Total Sales',money(sum('totalSales'))],['Payments Received',money(sum('paymentsReceived'))],['Outstanding',money(sum('outstanding'))],['Over Credit Limit',number(rows.filter(x=>x.creditStatus==='Over Limit').length)]]
  if(mode==='collections'){const by=(method)=>rows.filter(x=>String(x.method).toLowerCase()===method).reduce((s,x)=>s+num(x.amountCollected),0),remaining=[...new Map(rows.map(x=>[x.invoiceNumber,x.remainingBalance])).values()].reduce((s,x)=>s+num(x),0);return [['Total Collections',money(sum('amountCollected'))],['Cash',money(by('cash'))],['Bank',money(by('bank'))],['Cheque',money(by('cheque'))],['Remaining',money(remaining)]]}
  if(mode==='performance')return [['Active Reps',number(rows.filter(x=>x.status==='Active').length)],['Total Sales',money(sum('sales'))],['Gross Profit',money(sum('grossProfit'))],['Collections',money(sum('collections'))],['Outstanding',money(sum('outstanding'))]]
  return [['Transactions',number(rows.length)],['Orders',number(rows.filter(x=>x.type.includes('Order')).length)],['Invoices',number(rows.filter(x=>x.type.includes('Invoice')).length)],['Collections',money(rows.filter(x=>x.type.includes('Payment Received')).reduce((s,x)=>s+num(x.amount),0))],['Rep Payments',money(rows.filter(x=>x.type==='Rep Payment Made').reduce((s,x)=>s+num(x.amount),0))]]
}

function FilterPanel({raw,range,setRange,draft,setDraft,apply,reset}) {
  const set=(key,value)=>setDraft(current=>({...current,[key]:value})); const years=[...new Set((raw.invoices||[]).map(x=>day(x.created_at).slice(0,4)).filter(Boolean))].sort().reverse()
  return <section className="rounded-xl border border-slate-200 bg-white p-4 dark:border-emerald-800 dark:bg-emerald-950/20 print:hidden">
    <div className="mb-3 flex flex-wrap gap-2">{[['today','Today'],['yesterday','Yesterday'],['week','This Week'],['month','This Month'],['last','Last Month'],['year','This Year']].map(([key,label])=><button key={key} className="action" onClick={()=>setRange(preset(key))}>{label}</button>)}</div>
    <div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">
      <input className="field" type="date" value={range.from} onChange={e=>setRange(x=>({...x,from:e.target.value}))}/><input className="field" type="date" value={range.to} onChange={e=>setRange(x=>({...x,to:e.target.value}))}/>
      <select className="field" value={draft.rep} onChange={e=>set('rep',e.target.value)}><option value="">All reps</option>{raw.employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
      <select className="field" value={draft.customer} onChange={e=>set('customer',e.target.value)}><option value="">All customers</option>{raw.customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
      <select className="field" value={draft.product} onChange={e=>set('product',e.target.value)}><option value="">All products</option>{raw.products.map(x=><option key={x.id} value={x.id}>{x.code || '-'} · {x.name}</option>)}</select>
      <input className="field" placeholder="Invoice number" value={draft.invoice} onChange={e=>set('invoice',e.target.value)}/>
      <select className="field" value={draft.month} onChange={e=>set('month',e.target.value)}><option value="">All months</option>{Array.from({length:12},(_,i)=><option key={i} value={i}>{new Date(2020,i,1).toLocaleString(undefined,{month:'long'})}</option>)}</select>
      <select className="field" value={draft.year} onChange={e=>set('year',e.target.value)}><option value="">All years</option>{years.map(x=><option key={x}>{x}</option>)}</select>
      <select className="field" value={draft.method} onChange={e=>set('method',e.target.value)}><option value="">All payment methods</option>{['cash','bank','cheque','other'].map(x=><option key={x}>{x}</option>)}</select>
      <select className="field" value={draft.commissionStatus} onChange={e=>set('commissionStatus',e.target.value)}><option value="">All commission statuses</option>{['Unpaid','Partial','Paid','Advance Available','Commission Due','Settled'].map(x=><option key={x}>{x}</option>)}</select>
      <select className="field" value={draft.paymentStatus} onChange={e=>set('paymentStatus',e.target.value)}><option value="">All payment statuses</option>{['paid','partial','unpaid'].map(x=><option key={x}>{x}</option>)}</select>
      <div className="relative"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input className="field w-full pl-9" placeholder="Search report" value={draft.search} onChange={e=>set('search',e.target.value)}/></div>
    </div>
    <div className="mt-3 flex justify-end gap-2"><button className="action" onClick={reset}><RefreshCw size={14}/>Reset</button><button className="action border-emerald-600 bg-emerald-600 !text-white" onClick={apply}><Filter size={14}/>Apply Filters</button></div>
  </section>
}

function ExportDocument({mode,range,filters,user,columns,rows,cards,repName}) {
  return <div id="rep-report-export" className="fixed left-[-99999px] top-0 w-[1100px] bg-white p-6 text-black print:static print:w-auto print:p-0">
    <header className="flex items-start justify-between border-b-2 border-black pb-3"><div className="flex gap-3"><img src={logo} className="h-14 w-14 object-contain"/><div><h1 className="text-xl font-bold">Shayan's Kids & Toys</h1><p>Wholesale Management System</p><b>{reportTitle(mode)}</b>{repName?<p>Rep: {repName}</p>:null}</div></div><div className="text-right text-xs"><p>Date Range: {range.from} to {range.to}</p><p>Generated By: {user||'-'}</p><p>Generated: {new Date().toLocaleString()}</p></div></header>
    <div className="my-3 grid grid-cols-5 gap-2 text-xs">{cards.map(([label,value])=><div key={label}><b>{label}</b><br/>{value}</div>)}</div>
    {mode==='settlement'&&rows.length===1?<section className="mx-auto mt-6 max-w-2xl rounded-xl border-2 border-slate-800 p-6"><h2 className="border-b pb-3 text-center text-lg font-bold">Monthly Commission Settlement</h2><div className="mt-4 grid grid-cols-2 gap-x-8 gap-y-3 text-sm">{columns.map(column=><React.Fragment key={column.key}><b className="border-b border-slate-200 py-1">{column.label}</b><span className="border-b border-slate-200 py-1 text-right">{display(rows[0],column)}</span></React.Fragment>)}</div><div className="mt-12 grid grid-cols-2 gap-16 text-center text-xs"><div className="border-t border-black pt-2">Rep Signature</div><div className="border-t border-black pt-2">Authorized Signature</div></div></section>:<table className="w-full border-collapse text-[8px]"><thead><tr>{columns.map(column=><th key={column.key} className="border border-slate-400 bg-slate-100 p-1 text-left">{column.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id||index}>{columns.map(column=><td key={column.key} className="border border-slate-300 p-1">{display(row,column)}</td>)}</tr>)}</tbody><tfoot><tr><td colSpan={columns.length} className="border border-slate-400 p-2 font-bold">Records: {rows.length} · {cards.map(([k,v])=>`${k}: ${v}`).join(' · ')}</td></tr></tfoot></table>}
    <footer className="mt-3 border-t border-slate-400 pt-1 text-center text-[8px]">Shayan's Kids & Toys · {reportTitle(mode)} · Page</footer>
  </div>
}

export default function RepCommissionReportsPage() {
  const {user}=useAuth(), {can,isSuperAdmin}=usePermissions(); const [mode,setMode]=useState('sales'),[range,setRange]=useState(()=>preset('year'))
  const [raw,setRaw]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[draft,setDraft]=useState(empty),[filters,setFilters]=useState(empty)
  const [sort,setSort]=useState({key:'date',dir:'desc'}),[page,setPage]=useState(1),[size,setSize]=useState(25),[visibleColumns,setVisibleColumns]=useState(null),[columnsOpen,setColumnsOpen]=useState(false)
  const load=async()=>{setLoading(true);setError('');const tables=['employees','orders','order_items','invoices','invoice_items','invoice_payments','customers','products','returns','return_items','rep_commission_payments','rep_payments','commissions','audit_logs'];const results=await Promise.all(tables.map(async table=>({table,...await supabase.from(table).select('*')})));const next={};let failure='';results.forEach(({table,data,error:e})=>{next[table]=data||[];if(e&&!['rep_commission_payments','rep_payments','commissions','return_items','audit_logs'].includes(table))failure=`${table}: ${e.message}`});next.employees=(next.employees||[]).filter(x=>x.is_rep===true);setRaw(next);setError(failure);setLoading(false)}
  useEffect(()=>{load()},[]); const model=useMemo(()=>raw?buildRepReportModel(raw):null,[raw]); useEffect(()=>{setPage(1);setVisibleColumns(null)},[mode,filters,range,size])
  const columns=REP_COLUMNS[mode], enabled=visibleColumns||columns.map(x=>x.key), shownColumns=columns.filter(x=>enabled.includes(x.key))
  const reportModel=useMemo(()=>{if(!raw||!['customers','performance'].includes(mode))return model;const within=x=>inDateRange(x,range.from,range.to),invoices=raw.invoices.filter(x=>within(x.created_at)),invoiceIds=new Set(invoices.map(x=>String(x.id))),orders=raw.orders.filter(x=>within(x.created_at)),orderIds=new Set(orders.map(x=>String(x.id)));return buildRepReportModel({...raw,invoices,invoice_items:raw.invoice_items.filter(x=>invoiceIds.has(String(x.invoice_id))),invoice_payments:raw.invoice_payments.filter(x=>invoiceIds.has(String(x.invoice_id))),returns:raw.returns.filter(x=>invoiceIds.has(String(x.invoice_id))&&within(x.created_at)),orders,order_items:raw.order_items.filter(x=>orderIds.has(String(x.order_id))),rep_commission_payments:raw.rep_commission_payments.filter(x=>within(x.paid_at||x.created_at)),rep_payments:raw.rep_payments.filter(x=>within(x.paid_at||x.created_at))})},[raw,model,mode,range])
  const filtered=useMemo(()=>{if(!reportModel)return[];let rows=baseRows(mode,reportModel).filter(row=>{const date=rowDate(mode,row);if(date&&!inDateRange(date,range.from,range.to))return false;if(filters.rep&&String(row.repId)!==String(filters.rep))return false;if(filters.customer&&String(row.customerId)!==String(filters.customer))return false;if(filters.product&&String(row.productId)!==String(filters.product))return false;if(filters.method&&String(row.method).toLowerCase()!==filters.method)return false;if(filters.commissionStatus&&row.status!==filters.commissionStatus)return false;if(filters.paymentStatus&&String(row.paymentStatus||'').toLowerCase()!==filters.paymentStatus)return false;if(filters.invoice&&!String(row.invoiceNumber||'').toLowerCase().includes(filters.invoice.toLowerCase()))return false;if(filters.month!==''&&date&&Number(row.monthIndex??new Date(date).getMonth())!==Number(filters.month))return false;if(filters.year&&date&&String(row.year??new Date(date).getFullYear())!==String(filters.year))return false;const q=filters.search.toLowerCase();return !q||Object.values(row).some(value=>['string','number'].includes(typeof value)&&String(value).toLowerCase().includes(q))});return rows},[reportModel,mode,filters,range])
  const sorted=useMemo(()=>[...filtered].sort((a,b)=>{const av=valueAt(a,sort.key),bv=valueAt(b,sort.key);if(av==null)return 1;if(bv==null)return-1;const result=typeof av==='number'?av-num(bv):String(av).localeCompare(String(bv),undefined,{numeric:true});return sort.dir==='asc'?result:-result}),[filtered,sort]);const pages=Math.max(1,Math.ceil(sorted.length/size)),visible=sorted.slice((page-1)*size,page*size),cards=summary(mode,filtered,reportModel)
  const exportRows=()=>sorted.map(row=>Object.fromEntries(shownColumns.map(column=>[column.label,valueAt(row,column.key)??''])))
  const excel=()=>{const book=XLSX.utils.book_new(),sheet=XLSX.utils.json_to_sheet(exportRows());XLSX.utils.book_append_sheet(book,sheet,reportTitle(mode).slice(0,31));XLSX.writeFile(book,`${mode}-rep-report.xlsx`)}
  const csv=()=>{const sheet=XLSX.utils.json_to_sheet(exportRows()),link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\ufeff'+XLSX.utils.sheet_to_csv(sheet)],{type:'text/csv'}));link.download=`${mode}-rep-report.csv`;link.click();URL.revokeObjectURL(link.href)}
  if(loading)return <LoadingSkeleton/>;if(!isSuperAdmin&&!can('reports_reps','view'))return <div className="rounded-xl bg-rose-50 p-6 text-rose-700">Rep Reports permission is required.</div>;if(!model)return <div className="rounded-xl bg-rose-50 p-6 text-rose-700">Unable to load Rep Reports. {error}</div>
  const selectedRep=raw.employees.find(x=>String(x.id)===String(filters.rep)), missingCostCount=raw.invoice_items.filter(x=>x.cost_price==null).length
  return <div className="space-y-5"><div className="space-y-5 print:hidden">
    <header className="rounded-lg border border-slate-200 bg-white p-4 dark:border-emerald-800 dark:bg-emerald-950/20"><p className="text-[10px] font-bold uppercase tracking-widest text-emerald-700">Rep & Commission Reports</p><h1 className="mt-1 text-xl font-bold text-slate-900 dark:text-white">{reportTitle(mode)}</h1><p className="text-sm text-slate-500">Sales, commissions, payments, advances, settlements, collections and factual rep performance.</p>{error?<p className="mt-2 text-sm text-amber-600">Report data warning: {error}</p>:null}{missingCostCount?<p className="mt-2 text-sm text-amber-600">{missingCostCount} invoice line{missingCostCount===1?'':'s'} have no historical cost snapshot. Their cost and gross profit are shown as unavailable, never replaced with current product cost.</p>:null}</header>
    <div className="flex gap-2 overflow-x-auto pb-1">{REP_REPORTS.map(([key,label])=><button key={key} onClick={()=>setMode(key)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${mode===key?'bg-emerald-600 text-white':'border border-slate-200 bg-white text-slate-600 dark:border-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-100'}`}>{label}</button>)}</div>
    <FilterPanel raw={raw} range={range} setRange={setRange} draft={draft} setDraft={setDraft} apply={()=>setFilters(draft)} reset={()=>{setDraft(empty);setFilters(empty);setRange(preset('year'))}}/>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-5">{cards.map(([label,value])=><div key={label} className="rounded-lg border border-slate-200 bg-white p-3 dark:border-emerald-800 dark:bg-emerald-950/20"><p className="text-[10px] font-bold uppercase text-slate-500">{label}</p><p className="mt-1 font-bold text-slate-900 dark:text-white">{value}</p></div>)}</div>
    <div className="flex flex-wrap items-center gap-2"><select className="field" value={sort.key} onChange={e=>setSort({key:e.target.value,dir:sort.dir})}>{columns.map(x=><option key={x.key} value={x.key}>Sort: {x.label}</option>)}</select><button className="action" onClick={()=>setSort(x=>({...x,dir:x.dir==='asc'?'desc':'asc'}))}>{sort.dir==='asc'?'Ascending':'Descending'}</button><div className="relative"><button className="action" onClick={()=>setColumnsOpen(x=>!x)}><SlidersHorizontal size={14}/>Columns</button>{columnsOpen?<div className="absolute right-0 z-30 mt-2 max-h-80 w-64 overflow-auto rounded-xl border bg-white p-3 shadow-xl dark:border-emerald-800 dark:bg-emerald-950">{columns.map(column=><label key={column.key} className="flex items-center gap-2 py-1 text-sm"><input type="checkbox" checked={enabled.includes(column.key)} onChange={()=>setVisibleColumns(current=>{const list=current||columns.map(x=>x.key);return list.includes(column.key)?list.filter(x=>x!==column.key):[...list,column.key]})}/>{column.label}</label>)}</div>:null}</div><span className="ml-auto text-sm text-slate-500">{sorted.length} filtered records</span>
      {(isSuperAdmin||can('reports_reps','print'))?<button className="action" onClick={()=>window.print()}><Printer size={14}/>Print</button>:null}{(isSuperAdmin||can('reports_reps','export'))?<><button className="action" onClick={()=>exportToPDF('rep-report-export',`${mode}-rep-report.pdf`,{orientation:mode==='settlement'?'portrait':'landscape',pageNumbers:true,scale:1.4})}><FileText size={14}/>PDF</button><button className="action" onClick={excel}><Download size={14}/>Excel</button><button className="action" onClick={csv}><Download size={14}/>CSV</button></>:null}
    </div>
    <div className="max-h-[68vh] overflow-auto rounded-lg border border-slate-200 bg-white dark:border-emerald-800 dark:bg-emerald-950/20"><table className="min-w-full text-xs"><thead className="sticky top-0 bg-slate-50 dark:bg-emerald-900"><tr>{shownColumns.map(column=><th key={column.key} className={`whitespace-nowrap p-3 font-semibold ${['money','number','percent'].includes(column.type)?'text-right':'text-left'}`}>{column.label}</th>)}</tr></thead><tbody>{visible.length?visible.map((row,index)=><tr key={row.id||index} className="border-t border-slate-100 dark:border-emerald-900/40">{shownColumns.map(column=><td key={column.key} className={`whitespace-nowrap p-3 ${['money','number','percent'].includes(column.type)?'text-right tabular-nums':''}`}>{display(row,column)}</td>)}</tr>):<tr><td colSpan={shownColumns.length} className="p-12 text-center text-slate-500">No records match the selected filters.</td></tr>}</tbody></table></div>
    <div className="flex items-center justify-between rounded-lg border bg-white p-3 dark:border-emerald-800 dark:bg-emerald-950/20"><span className="text-sm text-slate-500">Page {page} of {pages}</span><div className="flex gap-2"><select className="field" value={size} onChange={e=>setSize(Number(e.target.value))}>{[10,25,50,100].map(x=><option key={x}>{x}</option>)}</select><button className="action" disabled={page===1} onClick={()=>setPage(x=>x-1)}>Previous</button><button className="action" disabled={page===pages} onClick={()=>setPage(x=>x+1)}>Next</button></div></div>
  </div><ExportDocument mode={mode} range={range} filters={filters} user={user?.email} columns={shownColumns} rows={sorted} cards={cards} repName={selectedRep?.name}/></div>
}
