import React,{useEffect}from'react'
import{ChevronRight}from'lucide-react'
import{Link,Navigate,useParams}from'react-router-dom'
import{useAuth}from'../../contexts/AuthContext';import{usePermissions}from'../../contexts/PermissionsContext'
import Admin from'./AdminSystemReportsPage';import Balance from'./BalanceSheetReportPage';import Cheques from'./ChequeReportsPage';import CustomerLedger from'./CustomerLedgerPage';import Customers from'./CustomerReportsPage';import CustomerStatement from'./CustomerStatementPage';import Expenses from'./ExpenseReportsPage';import Finance from'./FinanceReportsPage';import Inventory from'./InventoryReportsPage';import LowStock from'./LowStockReportPage';import CurrentStock from'./CurrentStockReportPage';import Receivables from'./OutstandingReceivablesReportPage';import ProfitLoss from'./ProfitLossReportPage';import Purchases from'./PurchaseReportsPage';import Reps from'./RepCommissionReportsPage';import Returns from'./ReturnsDeliveryReportsPage';import Sales from'./SalesReportsPage';import Vendors from'./VendorReportsPage';import Backorder from'../BackorderReportPage'
import{findReport,reportAction,reportPath,userStorageKey}from'./reportCatalog'
export default function ReportRoutePage(){const{categoryKey,reportSlug}=useParams(),match=findReport(categoryKey,reportSlug),{user}=useAuth(),{can,isSuperAdmin}=usePermissions(),path=match?reportPath(match.category,match.report):''
 useEffect(()=>{if(!match)return;try{const key=userStorageKey(user,'recent'),old=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify([path,...old.filter(x=>x!==path)].slice(0,5)))}catch{}},[path,user])
 if(!match)return <Navigate to="/reports" replace/>;if(!isSuperAdmin&&!can(match.report.module,reportAction(match.report)))return <Navigate to={`/reports/${categoryKey}`} replace/>
 const{renderer,mode}=match.report;let page=null
 if(renderer==='sales')page=<Sales initialMode={mode}/>;else if(renderer==='purchase')page=<Purchases initialMode={mode}/>;else if(renderer==='inventory')page=<Inventory initialTab={mode}/>;else if(renderer==='current-stock')page=<CurrentStock/>;else if(renderer==='low-stock')page=<LowStock/>;else if(renderer==='backorder')page=<Backorder/>;else if(renderer==='customer')page=<Customers/>;else if(renderer==='customer-statement')page=<CustomerStatement/>;else if(renderer==='customer-ledger')page=<CustomerLedger/>;else if(renderer==='outstanding-receivables')page=<Receivables/>;else if(renderer==='vendor')page=<Vendors initialMode={mode}/>;else if(renderer==='rep')page=<Reps initialMode={mode}/>;else if(renderer==='finance')page=<Finance initialMode={mode}/>;else if(renderer==='profit-loss')page=<ProfitLoss/>;else if(renderer==='balance-sheet')page=<Balance/>;else if(renderer==='expenses')page=<Expenses/>;else if(renderer==='cheque')page=<Cheques initialMode={mode}/>;else if(renderer==='returns')page=<Returns initialMode={mode}/>;else if(renderer==='admin')page=<Admin initialMode={mode}/>
 if(!page)return <Navigate to="/reports" replace/>
 return <div className="space-y-4"><nav className="flex flex-wrap items-center gap-1 text-sm text-slate-500 dark:text-emerald-100/60"><Link to="/reports">Reports</Link><ChevronRight size={15}/><Link to={`/reports/${categoryKey}`}>{match.category.title}</Link><ChevronRight size={15}/><b className="text-slate-800 dark:text-emerald-50">{match.report.name}</b></nav>{page}</div>
}
