import { BadgeDollarSign, Banknote, Boxes, ClipboardCheck, PackageCheck, ReceiptText, RotateCcw, ShoppingCart, TrendingUp, Users } from 'lucide-react'
const r=(slug,name,renderer,mode,module,keywords='')=>({slug,name,renderer,mode,module,keywords})
export const REPORT_CATEGORIES=[
 {key:'sales',title:'Sales Reports',icon:TrendingUp,description:'Sales performance, invoices, profit and product or customer analysis.',reports:[
 r('daily','Daily Sales Report','sales','daily','invoices'),r('monthly','Monthly Sales Report','sales','monthly','invoices'),r('by-customer','Sales by Customer','sales','customer','invoices'),r('by-product','Sales by Product','sales','product','invoices'),r('by-sales-rep','Sales by Sales Rep','sales','rep','invoices'),r('profit','Sales Profit Report','sales','daily','invoices','gross profit'),r('items-with-cost','Sales Item with Cost','sales','daily','invoices','historical cost'),r('invoice-discounts','Invoice Discount Report','sales','daily','invoices'),r('top-moving-products','Top Moving Products','sales','product','invoices'),r('order-summary','Order Summary','sales','daily','orders'),r('pending-order-items','Pending Order Items','sales','daily','orders')]},
 {key:'purchases',title:'Purchase Reports',icon:ShoppingCart,description:'Purchases, vendors, products, payments, credit and cost analysis.',reports:[
 r('detailed','Detailed Purchase Report','purchase','detailed','reports_purchase'),r('summary','Purchase Summary','purchase','monthly','reports_purchase'),r('by-vendor','Purchase by Vendor','purchase','vendor','reports_purchase'),r('by-product','Purchase by Product','purchase','product','reports_purchase'),r('items','Purchase Item Report','purchase','detailed','reports_purchase'),r('payments','Purchase Payment Report','purchase','payments','reports_purchase'),r('credit','Credit Purchase Report','purchase','outstanding','reports_purchase'),r('cost-analysis','Purchase Cost Analysis','purchase','cost','reports_purchase')]},
 {key:'inventory',title:'Inventory Reports',icon:Boxes,description:'Stock levels, valuation, movements, exceptions and product cost history.',reports:[
 r('detailed','Detailed Inventory Report','inventory','detailed','reports_inventory'),r('current-stock','Current Stock Report','current-stock','','products'),r('valuation','Stock Valuation Report','inventory','valuation','reports_inventory'),r('low-stock','Low Stock Report','low-stock','','products'),r('zero-stock','Zero Stock Report','inventory','out','reports_inventory'),r('backorder','Negative Stock / Backorder Report','backorder','','products'),r('beginning-stock','Beginning Stock Report','inventory','summary','inventory_beginning_stock'),r('movement','Stock Movement Report','inventory','movement','reports_inventory'),r('product-cost-history','Product Cost History','inventory','detailed','reports_inventory')]},
 {key:'customers',title:'Customer & Receivable Reports',icon:Users,description:'Customer accounts, statements, receivables, payments and sales history.',reports:[
 r('summary','Customer Summary','customer','','reports_customers'),r('statement','Customer Statement','customer-statement','','reports_customers'),r('ledger','Customer Ledger','customer-ledger','','finance_receivables'),r('outstanding-receivables','Outstanding Receivables','outstanding-receivables','','finance_receivables'),r('receivable-aging','Receivable Aging','finance','receivables','reports_finance'),r('payments-received','Payment Received Report','finance','receivables','reports_finance'),r('sales-history','Customer Sales History','customer','','reports_customers'),r('product-history','Customer Product History','customer','','reports_customers'),r('return-history','Customer Return History','customer','','reports_customers')]},
 {key:'vendors',title:'Vendor & Payable Reports',icon:PackageCheck,description:'Vendor accounts, statements, payables, payments and purchase history.',reports:[
 r('summary','Vendor Summary','vendor','overview','reports_vendors'),r('statement','Vendor Statement','vendor','statement','reports_vendors'),r('ledger','Vendor Ledger','vendor','ledger','reports_vendors'),r('payables','Outstanding Payables','vendor','outstanding','reports_vendors'),r('payable-aging','Payable Aging','vendor','aging','reports_vendors'),r('payments-made','Payment Made Report','vendor','payments','reports_vendors'),r('purchase-history','Vendor Purchase History','vendor','purchases','reports_vendors')]},
 {key:'reps',title:'Rep & Commission Reports',icon:BadgeDollarSign,description:'Rep sales, commissions, payments, advances and settlements.',reports:[
 r('sales','Rep Sales Report','rep','sales','reports_reps'),r('commission-summary','Commission Summary','rep','monthly','reports_reps'),r('commission-details','Commission Details','rep','sales','reports_reps'),r('payments','Rep Payment Report','rep','payments','reports_reps'),r('advances','Rep Advance Report','rep','advances','reports_reps'),r('settlements','Rep Settlement Report','rep','settlement','reports_reps'),r('customer-outstanding','Rep Customer Outstanding Report','rep','customers','reports_reps')]},
 {key:'finance',title:'Finance & Accounting Reports',icon:Banknote,description:'Financial statements, ledgers, journals, income, expenses and bank activity.',reports:[
 r('profit-loss','Profit & Loss','profit-loss','','reports_profit_loss'),r('balance-sheet','Balance Sheet','balance-sheet','','reports_balance_sheet'),r('trial-balance','Trial Balance','finance','trial-balance','reports_finance'),r('general-ledger','General Ledger','finance','general-ledger','reports_finance'),r('journal-statement','Journal Statement','finance','journals','reports_finance'),r('expense-summary','Expense Summary','expenses','','reports_expenses'),r('income-summary','Income Summary','finance','profit-loss','reports_finance'),r('bank-statement','Bank Statement','finance','bank-book','reports_finance'),r('bank-reconciliation','Bank Reconciliation Report','finance','bank-reconciliation','reports_finance')]},
 {key:'cheques',title:'Cheque Reports',icon:ReceiptText,description:'Customer and vendor cheque status, deposits, returns and summaries.',reports:[
 r('in-hand','Cheques in Hand','cheque','in-hand','reports_cheques'),r('deposited','Deposited Cheques','cheque','deposited','reports_cheques'),r('returned','Returned Cheques','cheque','returned','reports_cheques'),r('customers','Customer Cheques','cheque','customer-history','reports_cheques'),r('vendors','Vendor Cheques','cheque','vendor-history','reports_cheques'),r('summary','Cheque Summary','cheque','summary','reports_cheques')]},
 {key:'returns',title:'Returns & Delivery Reports',icon:RotateCcw,description:'Sales returns, returned items and order delivery status.',reports:[
 r('sales-returns','Sales Return Report','returns','detailedReturns','reports_returns_delivery'),r('return-items','Return Item Report','returns','detailedReturns','reports_returns_delivery'),r('by-customer','Returns by Customer','returns','returnsByCustomer','reports_returns_delivery'),r('by-product','Returns by Product','returns','returnsByProduct','reports_returns_delivery'),r('by-rep','Returns by Rep','returns','returnsByRep','reports_returns_delivery'),r('delivery','Delivery Report','returns','deliveryRows','reports_returns_delivery'),r('pending-deliveries','Pending Deliveries','returns','pendingDelivery','reports_returns_delivery'),r('delivered-orders','Delivered Orders','returns','deliveredOrders','reports_returns_delivery')]},
 {key:'admin',title:'Admin & Audit Reports',icon:ClipboardCheck,description:'Audit, user activity, permissions, security and backup history.',reports:[
 r('audit-log','Audit Log Report','admin','audit','reports_admin_system'),r('user-activity','User Activity Report','admin','userActivity','reports_admin_system'),r('login-activity','Login Activity','admin','security','reports_admin_system'),r('deleted-records','Deleted Records Report','admin','deleted','reports_admin_system'),r('permissions','User Permission Report','admin','privileges','reports_admin_system'),r('backup-summary','Database / Backup Summary','admin','backup','reports_admin_system')]},
]
export const categoryPath=c=>`/reports/${c.key}`
export const reportPath=(c,x)=>`${categoryPath(c)}/${x.slug}`
export const findCategory=key=>REPORT_CATEGORIES.find(c=>c.key===key)
export const findReport=(categoryKey,slug)=>{const category=findCategory(categoryKey),report=category?.reports.find(x=>x.slug===slug);return category&&report?{category,report}:null}
export const reportAction=item=>item.renderer==='finance'?({receivables:'view_receivables','bank-book':'view_bank_data','bank-reconciliation':'view_bank_data','profit-loss':'view_profit_loss'}[item.mode]||'view'):'view'
export const userStorageKey=(user,suffix)=>`shayan-reports:${user?.id||user?.email||'anonymous'}:${suffix}`
