import React,{useEffect,useMemo,useState}from'react'
import*as XLSX from'xlsx'
import{Columns3,Download,FileText,Filter,Printer,RefreshCw,Search}from'lucide-react'
import{supabase}from'../../lib/supabaseClient'
import{useAuth}from'../../contexts/AuthContext'
import{usePermissions}from'../../contexts/PermissionsContext'
import{LoadingSkeleton,exportToPDF}from'../../components/reports'
import{buildReturnsDeliveryReports,reportMath}from'../../lib/returnsDeliveryReports'
import logo from'../../pictures/logo.jpeg'

const{number:n,sum}=reportMath,money=v=>`Rs. ${n(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`,num=v=>n(v).toLocaleString(undefined,{maximumFractionDigits:2}),date=v=>v?new Date(v).toLocaleDateString():'-',dateTime=v=>v?new Date(v).toLocaleString():'-'
const C=(key,label,type='text')=>({key,label,type})
const REPORTS=[['detailedReturns','Detailed Returns Report'],['returnsByCustomer','Returns by Customer'],['returnsByProduct','Returns by Product'],['returnsByRep','Returns by Sales Rep'],['returnValue','Return Value Report'],['deliveryRows','Delivery Report'],['pendingDelivery','Pending Delivery Report'],['deliveredOrders','Delivered Orders Report'],['deliveryByCustomer','Delivery by Customer'],['deliveryByRep','Delivery by Sales Rep'],['deliveryPerformance','Delivery Performance Report']]
const COLUMNS={
 detailedReturns:[C('returnNumber','Return Number'),C('date','Return Date','date'),C('customer','Customer'),C('phone','Customer Phone'),C('invoiceNumber','Original Invoice Number'),C('orderNumber','Original Order Number'),C('salesRep','Sales Rep'),C('productCode','Product Code'),C('productName','Product Name'),C('quantity','Quantity Returned','number'),C('unitPrice','Unit Price','money'),C('returnAmount','Return Amount','money'),C('reason','Reason'),C('status','Status','status'),C('stockUpdated','Stock Updated'),C('createdBy','Created By'),C('createdAt','Created Date/Time','datetime')],
 returnsByCustomer:[C('customer','Customer'),C('phone','Phone'),C('numberOfReturns','Number of Returns','number'),C('quantityReturned','Quantity Returned','number'),C('returnValue','Return Value','money'),C('totalSales','Total Sales','money'),C('returnPercentage','Return Percentage','percent'),C('lastReturnDate','Last Return Date','date'),C('outstandingBalance','Outstanding Balance','money')],
 returnsByProduct:[C('productCode','Product Code'),C('productName','Product Name'),C('quantitySold','Quantity Sold','number'),C('quantityReturned','Quantity Returned','number'),C('netQuantitySold','Net Quantity Sold','number'),C('returnValue','Return Value','money'),C('returnRate','Return Rate','percent'),C('lastReturnDate','Last Return Date','date')],
 returnsByRep:[C('salesRep','Sales Rep'),C('invoices','Number of Invoices','number'),C('salesValue','Sales Value','money'),C('numberOfReturns','Number of Returns','number'),C('returnQuantity','Return Quantity','number'),C('returnValue','Return Value','money'),C('returnPercentage','Return Percentage','percent'),C('customersWithReturns','Customers with Returns','number')],
 returnValue:[C('returnNumber','Return Number'),C('date','Date','date'),C('customer','Customer'),C('invoiceNumber','Invoice Number'),C('productName','Product'),C('quantity','Quantity','number'),C('originalSaleValue','Original Sale Value','money'),C('returnAmount','Return Value','money'),C('netSaleAfterReturn','Net Sale After Return','money')],
 deliveryRows:[C('orderNumber','Order Number'),C('invoiceNumber','Invoice Number'),C('orderDate','Order Date','date'),C('invoiceDate','Invoice Date','date'),C('customer','Customer'),C('phone','Customer Phone'),C('address','Address'),C('salesRep','Sales Rep'),C('orderTotal','Order Total','money'),C('deliveryStatus','Delivery Status','status'),C('deliveredDate','Delivered Date','date'),C('daysToDeliver','Days to Deliver','days'),C('createdBy','Created By')],
 pendingDelivery:[C('orderNumber','Order Number'),C('invoiceNumber','Invoice Number'),C('customer','Customer'),C('phone','Phone'),C('address','Address'),C('salesRep','Sales Rep'),C('orderDate','Order Date','date'),C('invoiceDate','Invoice Date','date'),C('orderTotal','Order Total','money'),C('daysPending','Days Pending','days'),C('deliveryStatus','Delivery Status','status')],
 deliveredOrders:[C('orderNumber','Order Number'),C('invoiceNumber','Invoice Number'),C('customer','Customer'),C('salesRep','Sales Rep'),C('orderDate','Order Date','date'),C('invoiceDate','Invoice Date','date'),C('deliveredDate','Delivered Date','date'),C('daysToDeliver','Days to Deliver','days'),C('orderTotal','Total Amount','money'),C('deliveredBy','Delivered By')],
 deliveryByCustomer:[C('customer','Customer'),C('phone','Phone'),C('totalOrders','Total Orders','number'),C('deliveredOrders','Delivered Orders','number'),C('pendingOrders','Pending Orders','number'),C('cancelledOrders','Cancelled Orders','number'),C('totalDeliveredValue','Total Delivered Value','money'),C('lastDeliveryDate','Last Delivery Date','date'),C('averageDeliveryTime','Average Delivery Time','days')],
 deliveryByRep:[C('salesRep','Sales Rep'),C('totalOrders','Orders','number'),C('invoices','Invoices','number'),C('deliveredOrders','Delivered','number'),C('pendingOrders','Pending','number'),C('cancelledOrders','Cancelled','number'),C('totalDeliveredValue','Delivery Value','money'),C('averageDeliveryTime','Average Delivery Time','days')],
 deliveryPerformance:[C('period','Period'),C('ordersCreated','Orders Created','number'),C('ordersInvoiced','Orders Invoiced','number'),C('delivered','Delivered','number'),C('pending','Pending','number'),C('cancelled','Cancelled','number'),C('deliveryRate','Delivery Rate','percent'),C('averageDeliveryDays','Average Delivery Days','days')]
}
const emptyFilters={customer:'',product:'',rep:'',returnStatus:'',deliveryStatus:'',invoice:'',order:'',search:''},iso=d=>d.toISOString().slice(0,10)
function presetRange(key){const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),to=new Date(today);let from=new Date(today);if(key==='yesterday'){from.setDate(from.getDate()-1);to.setDate(to.getDate()-1)}if(key==='week')from.setDate(from.getDate()-((from.getDay()+6)%7));if(key==='month')from=new Date(today.getFullYear(),today.getMonth(),1);if(key==='last'){from=new Date(today.getFullYear(),today.getMonth()-1,1);to.setDate(0)}if(key==='year')from=new Date(today.getFullYear(),0,1);return{from:iso(from),to:iso(to)}}
const reportName=mode=>REPORTS.find(([key])=>key===mode)?.[1]||'Returns & Delivery Report',rawValue=(row,key)=>key.split('.').reduce((value,part)=>value?.[part],row)
function display(row,column){const value=rawValue(row,column.key);if(column.type==='money')return money(value);if(column.type==='number')return num(value);if(column.type==='percent')return`${n(value).toFixed(2)}%`;if(column.type==='date')return date(value);if(column.type==='datetime')return dateTime(value);if(column.type==='days')return value==null?'-':`${num(value)} days`;if(column.type==='status')return String(value||'-').replace(/\b\w/g,x=>x.toUpperCase());return value==null||value===''?'-':String(value)}
function Filters({raw,range,setRange,draft,setDraft,apply,reset}){
 const set=(key,value)=>setDraft(f=>({...f,[key]:value})),presets=[['today','Today'],['yesterday','Yesterday'],['week','This Week'],['month','This Month'],['last','Last Month'],['year','This Year']]
 return <section className="rounded-xl border border-slate-200 bg-white p-4 dark:border-emerald-800 dark:bg-emerald-950/20">
  <div className="mb-3 flex flex-wrap gap-2">{presets.map(([k,l])=><button key={k} className="action" onClick={()=>setRange(presetRange(k))}>{l}</button>)}</div>
  <div className="grid gap-3 md:grid-cols-3 xl:grid-cols-5">
   <input className="field" type="date" value={range.from} onChange={e=>setRange(r=>({...r,from:e.target.value}))}/><input className="field" type="date" value={range.to} onChange={e=>setRange(r=>({...r,to:e.target.value}))}/>
   <select className="field" value={draft.customer} onChange={e=>set('customer',e.target.value)}><option value="">All customers</option>{raw.customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
   <select className="field" value={draft.product} onChange={e=>set('product',e.target.value)}><option value="">All products</option>{raw.products.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select>
   <select className="field" value={draft.rep} onChange={e=>set('rep',e.target.value)}><option value="">All sales reps</option>{raw.employees.filter(x=>x.is_rep!==false).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
   <select className="field" value={draft.returnStatus} onChange={e=>set('returnStatus',e.target.value)}><option value="">All return statuses</option>{[...new Set(raw.returns.map(x=>x.status||'completed'))].map(x=><option key={x}>{x}</option>)}</select>
   <select className="field" value={draft.deliveryStatus} onChange={e=>set('deliveryStatus',e.target.value)}><option value="">All delivery statuses</option>{['pending','invoiced','delivered','cancelled'].map(x=><option key={x}>{x}</option>)}</select>
   <input className="field" placeholder="Invoice number" value={draft.invoice} onChange={e=>set('invoice',e.target.value)}/><input className="field" placeholder="Order number" value={draft.order} onChange={e=>set('order',e.target.value)}/>
   <div className="relative"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input className="field w-full pl-9" placeholder="Search filtered report" value={draft.search} onChange={e=>set('search',e.target.value)}/></div>
  </div><div className="mt-3 flex justify-end gap-2"><button className="action" onClick={reset}><RefreshCw size={14}/>Reset Filters</button><button className="action border-emerald-600 bg-emerald-600 !text-white" onClick={apply}><Filter size={14}/>Apply Filters</button></div>
 </section>
}
function Cards({cards}){return<div className="grid grid-cols-2 gap-3 md:grid-cols-5">{cards.map(([l,v])=><div key={l} className="rounded-lg border border-slate-200 bg-white p-3 dark:border-emerald-800 dark:bg-emerald-950/20"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{l}</p><p className="mt-1 font-bold tabular-nums text-slate-900 dark:text-white">{v}</p></div>)}</div>}
function Table({columns,rows,sort,setSort}){return<div className="max-h-[65vh] overflow-auto rounded-lg border border-slate-200 bg-white dark:border-emerald-800 dark:bg-emerald-950/20"><table className="min-w-full text-xs"><thead className="sticky top-0 z-10 bg-slate-50 dark:bg-emerald-900"><tr>{columns.map(c=><th key={c.key} onClick={()=>setSort({key:c.key,dir:sort.key===c.key&&sort.dir==='asc'?'desc':'asc'})} className={`cursor-pointer whitespace-nowrap p-3 font-semibold ${['money','number','percent','days'].includes(c.type)?'text-right':'text-left'}`}>{c.label}{sort.key===c.key?(sort.dir==='asc'?' ↑':' ↓'):''}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||r.returnId||r.productId||r.customerId||r.repId||i} className="border-t border-slate-100 hover:bg-emerald-50/60 dark:border-emerald-900/40 dark:hover:bg-emerald-900/20">{columns.map(c=><td key={c.key} className={`whitespace-nowrap p-3 tabular-nums text-slate-700 dark:text-emerald-50/80 ${['money','number','percent','days'].includes(c.type)?'text-right':''}`}>{display(r,c)}</td>)}</tr>):<tr><td colSpan={columns.length} className="p-12 text-center text-slate-500">No records match the selected filters.</td></tr>}</tbody></table></div>}
function ExportDocument({mode,range,filters,user,columns,rows,cards}){return<div id="returns-delivery-export" className="returns-delivery-export fixed left-[-99999px] top-0 w-[1100px] bg-white p-6 text-black print:static print:w-auto print:p-0"><div className="flex items-start justify-between border-b-2 border-black pb-3"><div className="flex gap-3"><img src={logo} alt="Company logo" className="h-14 w-14 object-contain"/><div><h1 className="text-xl font-bold">Shayan's Kids & Toys</h1><p>Wholesale Management System</p><b>{reportName(mode)}</b></div></div><div className="max-w-[45%] text-right text-xs"><p>Selected date range: {range.from} to {range.to}</p><p>Generated by: {user||'-'}</p><p>Generated date: {new Date().toLocaleString()}</p><p>Applied filters: {Object.entries(filters).filter(([,v])=>v).map(([k,v])=>`${k}: ${v}`).join(', ')||'None'}</p></div></div><div className="my-3 grid grid-cols-5 gap-2 text-xs">{cards.map(([l,v])=><div key={l}><b>{l}</b><br/>{v}</div>)}</div><table className="w-full border-collapse text-[8px]"><thead><tr>{columns.map(c=><th key={c.key} className="border border-slate-400 bg-slate-100 p-1 text-left">{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c.key} className="border border-slate-300 p-1 align-top">{display(r,c)}</td>)}</tr>)}</tbody><tfoot><tr><td colSpan={columns.length} className="border border-slate-400 p-1 font-bold">Total filtered records: {rows.length}</td></tr></tfoot></table><div className="mt-3 border-t border-slate-400 pt-1 text-center text-[8px]">Shayan's Kids & Toys · {reportName(mode)} · Page</div></div>}

function summaryCards(mode,rows,model){
 const qty=v=>num(v),returns=model.detailedReturns||[],returnTotal=sum(returns,'returnAmount'),delivery=model.deliveryRows||[],delivered=model.deliveredOrders||[],pending=model.pendingDelivery||[],avg=list=>list.length?sum(list,r=>r.daysToDeliver)/list.length:0
 if(mode==='detailedReturns')return[['Total Returns',qty(new Set(rows.map(r=>r.returnId)).size)],['Return Quantity',qty(sum(rows,'quantity'))],['Return Value',money(sum(rows,'returnAmount'))],['Customers',qty(new Set(rows.map(r=>r.customerId)).size)],['Products',qty(new Set(rows.map(r=>r.productId)).size)]]
 if(mode==='returnsByCustomer'){const top=[...rows].sort((a,b)=>b.returnValue-a.returnValue)[0];return[['Highest Return Customer',top?.customer||'-'],['Customers with Returns',qty(rows.length)],['Total Return Value',money(sum(rows,'returnValue'))]]}
 if(mode==='returnsByProduct'){const most=[...rows].sort((a,b)=>b.quantityReturned-a.quantityReturned)[0],high=[...rows].sort((a,b)=>b.returnValue-a.returnValue)[0];return[['Most Returned Product',most?.productName||'-'],['Highest Return Value Product',high?.productName||'-'],['Quantity Returned',qty(sum(rows,'quantityReturned'))]]}
 if(mode==='returnsByRep')return[['Sales Reps',qty(rows.length)],['Returns',qty(sum(rows,'numberOfReturns'))],['Return Quantity',qty(sum(rows,'returnQuantity'))],['Return Value',money(sum(rows,'returnValue'))]]
 if(mode==='returnValue'){const gross=model.invoiceSalesTotal;return[['Gross Sales',money(gross)],['Total Returns',money(returnTotal)],['Net Sales After Returns',money(gross-returnTotal)]]}
 if(mode==='pendingDelivery'){const oldest=Math.max(0,...rows.map(r=>n(r.daysPending)));return[['Pending Deliveries',qty(rows.length)],['Total Pending Value',money(sum(rows,'orderTotal'))],['Oldest Pending Delivery',`${oldest} days`],['Average Days Pending',`${rows.length?(sum(rows,'daysPending')/rows.length).toFixed(1):0} days`]]}
 if(mode==='deliveredOrders'){const times=rows.map(r=>n(r.daysToDeliver));return[['Total Deliveries',qty(rows.length)],['Delivered Value',money(sum(rows,'orderTotal'))],['Average Delivery Time',`${avg(rows).toFixed(1)} days`],['Fastest Delivery',`${times.length?Math.min(...times):0} days`],['Longest Delivery',`${times.length?Math.max(...times):0} days`]]}
 if(['deliveryByCustomer','deliveryByRep'].includes(mode))return[['Groups',qty(rows.length)],['Orders',qty(sum(rows,'totalOrders'))],['Delivered',qty(sum(rows,'deliveredOrders'))],['Pending',qty(sum(rows,'pendingOrders'))],['Delivered Value',money(sum(rows,'totalDeliveredValue'))]]
 if(mode==='deliveryPerformance')return[['Orders Created',qty(sum(rows,'ordersCreated'))],['Invoiced',qty(sum(rows,'ordersInvoiced'))],['Delivered',qty(sum(rows,'delivered'))],['Pending',qty(sum(rows,'pending'))],['Cancelled',qty(sum(rows,'cancelled'))]]
 return[['Pending',qty(pending.length)],['Delivered',qty(delivered.length)],['Total Delivery Value',money(sum(delivered,'orderTotal'))],['Average Delivery Days',`${avg(delivered).toFixed(1)} days`],['All Orders',qty(delivery.length)]]
}

export default function ReturnsDeliveryReportsPage(){
 const{user}=useAuth(),{can,isSuperAdmin}=usePermissions()
 const[mode,setMode]=useState('detailedReturns'),[range,setRange]=useState(()=>presetRange('month')),[draft,setDraft]=useState(emptyFilters),[filters,setFilters]=useState(emptyFilters),[raw,setRaw]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[sort,setSort]=useState({key:'date',dir:'desc'}),[grouping,setGrouping]=useState('month'),[hidden,setHidden]=useState(new Set())
 const load=async()=>{
  setLoading(true);setError('')
  const results=await Promise.all([supabase.from('customers').select('*').order('name'),supabase.from('employees').select('*').order('name'),supabase.from('products').select('*').order('name'),supabase.from('invoices').select('*'),supabase.from('invoice_items').select('*'),supabase.from('returns').select('*'),supabase.from('return_items').select('*'),supabase.from('orders').select('*'),supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(10000),supabase.from('invoice_payments').select('*')])
  const failed=results.slice(0,8).find(r=>r.error)
  if(failed){setError(failed.error.message);setRaw(null)}else setRaw({customers:results[0].data||[],employees:results[1].data||[],products:results[2].data||[],invoices:results[3].data||[],invoiceItems:results[4].data||[],returns:results[5].data||[],returnItems:results[6].data||[],orders:results[7].data||[],auditLogs:results[8].error?[]:results[8].data||[],invoicePayments:results[9].error?[]:results[9].data||[]})
  setLoading(false)
 }
 useEffect(()=>{load()},[])
 useEffect(()=>{setPage(1);setHidden(new Set());setSort({key:COLUMNS[mode][0].key,dir:'desc'})},[mode,range,filters,grouping,pageSize])
 const model=useMemo(()=>raw?buildReturnsDeliveryReports(raw,range,filters):null,[raw,range,filters])
 const base=useMemo(()=>model?(mode==='deliveryPerformance'?model.deliveryPerformance(grouping):model[mode]||[]):[],[model,mode,grouping]),allColumns=COLUMNS[mode],columns=allColumns.filter(c=>!hidden.has(c.key))
 const searched=useMemo(()=>{const q=filters.search.trim().toLowerCase();return q?base.filter(r=>allColumns.some(c=>String(rawValue(r,c.key)||'').toLowerCase().includes(q))):base},[base,filters.search,allColumns])
 const sorted=useMemo(()=>[...searched].sort((a,b)=>{let x=rawValue(a,sort.key),y=rawValue(b,sort.key);if(['date','datetime'].includes(allColumns.find(c=>c.key===sort.key)?.type)){x=x?new Date(x).getTime():0;y=y?new Date(y).getTime():0}return(x>y?1:x<y?-1:0)*(sort.dir==='asc'?1:-1)}),[searched,sort,allColumns])
 const pages=Math.max(1,Math.ceil(sorted.length/pageSize)),visible=sorted.slice((page-1)*pageSize,page*pageSize),cards=useMemo(()=>model?summaryCards(mode,searched,model):[],[mode,searched,model])
 const exportRows=()=>sorted.map(r=>Object.fromEntries(columns.map(c=>[c.label,rawValue(r,c.key)??''])))
 const excel=()=>{const book=XLSX.utils.book_new(),sheet=XLSX.utils.json_to_sheet(exportRows());XLSX.utils.book_append_sheet(book,sheet,reportName(mode).slice(0,31));XLSX.writeFile(book,`${mode}-report.xlsx`)}
 const csv=()=>{const sheet=XLSX.utils.json_to_sheet(exportRows()),blob=new Blob(['\ufeff'+XLSX.utils.sheet_to_csv(sheet)],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${mode}-report.csv`;link.click();URL.revokeObjectURL(link.href)}
 if(loading)return<LoadingSkeleton/>
 if(!isSuperAdmin&&!can('reports_returns_delivery','view'))return<div className="rounded-xl bg-rose-50 p-6 text-rose-700">Returns & Delivery Reports view permission is required.</div>
 if(!model)return<div className="rounded-xl border border-rose-200 bg-rose-50 p-6 text-rose-700">Could not load Returns & Delivery Reports: {error||'Unknown error'} <button className="ml-2 underline" onClick={load}>Retry</button></div>
 return <div className="space-y-5">
  <div className="returns-delivery-screen space-y-5">
   <header className="rounded-lg border border-slate-200 bg-white p-4 dark:border-emerald-800 dark:bg-emerald-950/20"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-widest text-emerald-700 dark:text-emerald-300">Returns & delivery reports</p><h1 className="mt-1 text-xl font-bold text-slate-900 dark:text-white">{reportName(mode)}</h1><p className="text-sm text-slate-500 dark:text-emerald-100/70">Historical returns and live order delivery status, with factual totals and operational detail.</p></div><div className="rounded-lg border bg-slate-50 px-3 py-2 text-sm dark:border-emerald-800 dark:bg-emerald-950/40"><b>{range.from}</b> to <b>{range.to}</b></div></div></header>
   <div className="flex gap-2 overflow-x-auto pb-1">{REPORTS.map(([key,label])=><button key={key} onClick={()=>setMode(key)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${mode===key?'bg-emerald-600 text-white':'border border-slate-200 bg-white text-slate-600 dark:border-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-100'}`}>{label}</button>)}</div>
   <Filters raw={raw} range={range} setRange={setRange} draft={draft} setDraft={setDraft} apply={()=>setFilters(draft)} reset={()=>{setDraft(emptyFilters);setFilters(emptyFilters);setRange(presetRange('month'))}}/>
   <Cards cards={cards}/>
   <div className="flex flex-wrap items-center gap-2">
    {mode==='deliveryPerformance'?<select className="field" value={grouping} onChange={e=>setGrouping(e.target.value)}><option value="day">Group by Day</option><option value="week">Group by Week</option><option value="month">Group by Month</option></select>:null}
    <details className="relative"><summary className="action cursor-pointer list-none"><Columns3 size={15}/>Columns</summary><div className="absolute left-0 z-20 mt-2 max-h-72 min-w-64 overflow-auto rounded-lg border bg-white p-3 shadow-xl dark:border-emerald-800 dark:bg-emerald-950">{allColumns.map(c=><label key={c.key} className="flex gap-2 py-1 text-sm"><input type="checkbox" checked={!hidden.has(c.key)} onChange={()=>setHidden(current=>{const next=new Set(current);next.has(c.key)?next.delete(c.key):next.add(c.key);return next})}/>{c.label}</label>)}</div></details>
    <span className="ml-auto text-sm text-slate-500">{num(sorted.length)} filtered records</span>
    {(isSuperAdmin||can('reports_returns_delivery','print'))?<button className="action" onClick={()=>window.print()}><Printer size={15}/>Print</button>:null}
    {(isSuperAdmin||can('reports_returns_delivery','export'))?<><button className="action" onClick={()=>exportToPDF('returns-delivery-export',`${mode}-report.pdf`,{orientation:'landscape',scale:1.35,pageNumbers:true})}><FileText size={15}/>PDF</button><button className="action" onClick={excel}><Download size={15}/>Excel</button><button className="action" onClick={csv}><Download size={15}/>CSV</button></>:null}
   </div>
   <Table columns={columns} rows={visible} sort={sort} setSort={setSort}/>
   <div className="flex items-center justify-between rounded-lg border bg-white p-3 dark:border-emerald-800 dark:bg-emerald-950/20"><span className="text-sm text-slate-500">Page {page} of {pages} · {sorted.length} records</span><div className="flex gap-2"><select className="field" value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}>{[10,25,50,100].map(v=><option key={v}>{v}</option>)}</select><button className="action" disabled={page===1} onClick={()=>setPage(v=>v-1)}>Previous</button><button className="action" disabled={page===pages} onClick={()=>setPage(v=>v+1)}>Next</button></div></div>
  </div>
  <ExportDocument mode={mode} range={range} filters={filters} user={user?.email} columns={columns} rows={sorted} cards={cards}/>
 </div>
}
