import React, { useEffect, useMemo, useState } from 'react'
import Chart from 'react-apexcharts'
import html2pdf from 'html2pdf.js'
import * as XLSX from 'xlsx'
import { Boxes, ChevronDown, ChevronRight, CircleDollarSign, Download, FileSpreadsheet, Filter, Landmark, Printer, RefreshCw, Scale, TrendingUp } from 'lucide-react'
import { useAuth } from '../../contexts/AuthContext'
import { supabase } from '../../lib/supabaseClient'
import { exportToExcel, exportToPDF, LoadingSkeleton } from '../../components/reports'
import logo from '../../pictures/logo.jpeg'
import { getCommissionRate } from '../../lib/repCommission'

const money = (value) => `Rs. ${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const number = (value) => Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 })
const isoDate = (date) => date.toISOString().slice(0, 10)
const startOfDay = (value) => new Date(`${value}T00:00:00`).toISOString()
const endOfDay = (value) => new Date(`${value}T23:59:59.999`).toISOString()

function presetRange(preset) {
  const now = new Date()
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())
  let start = new Date(today), end = new Date(today)
  if (preset === 'yesterday') start.setDate(start.getDate() - 1), end = new Date(start)
  if (preset === 'this-week') start.setDate(start.getDate() - ((start.getDay() + 6) % 7))
  if (preset === 'this-month') start = new Date(today.getFullYear(), today.getMonth(), 1)
  if (preset === 'last-month') {
    start = new Date(today.getFullYear(), today.getMonth() - 1, 1)
    end = new Date(today.getFullYear(), today.getMonth(), 0)
  }
  return { start: isoDate(start), end: isoDate(end) }
}

const emptyFilters = { customer: '', product: '', rep: '', invoice: '', payment: '', status: '' }

async function fetchReportData(start, end) {
  const [invoiceResult, paymentResult, productResult, purchaseResult, orderResult] = await Promise.all([
    supabase.from('invoices').select(`
      id, invoice_number, created_at, customer_id, rep_id, payment_type, total_amount,
      customers(id, name, phone, address), employees(id, name),
      invoice_items(id, product_id, quantity, price, discount, total)
    `).gte('created_at', startOfDay(start)).lte('created_at', endOfDay(end)).order('created_at', { ascending: false }),
    supabase.from('invoice_payments').select('id, invoice_id, amount, paid_at, method'),
    supabase.from('products').select('id, name, code, price, stock').order('name'),
    supabase.from('purchase_items').select('id, product_id, quantity, cost, purchases(date, created_at, status)'),
    supabase.from('orders').select('id, rep_id').gte('created_at', startOfDay(start)).lte('created_at', endOfDay(end)),
  ])
  if (invoiceResult.error) throw invoiceResult.error
  if (productResult.error) throw productResult.error
  return { invoices: invoiceResult.data || [], payments: paymentResult.error ? [] : (paymentResult.data || []), products: productResult.data || [], variants: [], purchases: purchaseResult.error ? [] : (purchaseResult.data || []).filter((x) => !['reversed','cancelled','canceled','deleted','void'].includes(String(x.purchases?.status ?? '').toLowerCase())), reportRows: [], rpcError: '', orders: orderResult.error ? [] : (orderResult.data || []) }
}

function PrintHeader({ title, generatedBy, range }) {
  return <div className="hidden print:flex items-start justify-between border-b-2 border-slate-900 pb-4 mb-5">
    <div className="flex gap-4"><img src={logo} className="h-16 w-16 object-contain" /><div><h1 className="text-xl font-bold">Shayan's Kids Care</h1><p className="text-xs">Wholesale Management System</p><p className="mt-2 font-semibold">{title}</p></div></div>
    <div className="text-right text-xs"><p>Generated by: {generatedBy}</p><p>Generated: {new Date().toLocaleString()}</p><p>Date range: {range.start} — {range.end}</p></div>
  </div>
}

function exportSalesReportPDF({ mode, title, range, generatedBy, model, exportRows }) {
  const escapeHtml = (value) => String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')

  const dailyColumns = [
    ['Invoice', 'Invoice'],
    ['Date', 'Invoice Date'],
    ['Customer', 'Customer'],
    ['Rep', 'Sales Rep'],
    ['Product', 'Product Name'],
    ['Code', 'Product Code'],
    ['Qty', 'Quantity Sold'],
    ['Unit Cost', 'Unit Cost', 'money'],
    ['Selling', 'Unit Selling Price', 'money'],
    ['Total Cost', 'Total Cost', 'money'],
    ['Sales', 'Sales Amount', 'money'],
    ['Profit', 'Gross Profit', 'money'],
    ['Profit %', 'Profit Margin %', 'percent'],
  ]

  const aggregateColumns = {
    monthly: [['Month','label'],['Invoices','invoices'],['Qty','quantity'],['Sales','sales','money'],['Cost','cost','money'],['Profit','profit','money'],['Profit %','margin','percent'],['Payments','payments','money'],['Outstanding','outstanding','money']],
    customer: [['Customer','name'],['Phone','phone'],['Invoices','invoices'],['Qty','quantity'],['Sales','sales','money'],['Payments','payments','money'],['Outstanding','outstanding','money'],['Credit Limit','creditLimit','money'],['Last Purchase','lastPurchase']],
    product: [['Product','name'],['Code','code'],['Opening','opening'],['Purchased','purchased'],['Sold','sold'],['Stock','current'],['Cost Price','averageCost','money'],['Selling','sellingPrice','money'],['Revenue','revenue','money'],['Cost Value','cost','money'],['Profit','profit','money'],['Profit %','margin','percent']],
    rep: [['Rep','name'],['Orders','orders'],['Invoices','invoices'],['Products','products'],['Sales','sales','money'],['Profit','profit','money'],['Commission','commission','money'],['Average','average','money']],
  }

  const columns = mode === 'daily' ? dailyColumns : aggregateColumns[mode]
  const rows = mode === 'daily' ? exportRows : model[mode]
  const formatCell = (row, key, type) => {
    const value = row[key]
    if (type === 'money') return money(value)
    if (type === 'percent') return `${Number(value || 0).toFixed(2)}%`
    return value ?? '-'
  }

  const body = rows.map((row) => `
    <tr>
      ${columns.map(([, key, type]) => `<td>${escapeHtml(formatCell(row, key, type))}</td>`).join('')}
    </tr>
  `).join('')

  const totals = model.totals
  const documentHtml = `
    <div class="sales-pdf">
      <div class="sales-pdf-header">
        <div>
          <h1>Shayan's Kids Care</h1>
          <p>Wholesale Management System</p>
          <h2>${escapeHtml(title)}</h2>
        </div>
        <div class="sales-pdf-meta">
          <p><b>Generated by:</b> ${escapeHtml(generatedBy)}</p>
          <p><b>Generated:</b> ${escapeHtml(new Date().toLocaleString())}</p>
          <p><b>Date range:</b> ${escapeHtml(range.start)} to ${escapeHtml(range.end)}</p>
        </div>
      </div>
      <div class="sales-pdf-summary">
        <span>Invoices: <b>${escapeHtml(number(totals.invoices))}</b></span>
        <span>Quantity: <b>${escapeHtml(number(totals.quantity))}</b></span>
        <span>Sales: <b>${escapeHtml(money(totals.sales))}</b></span>
        <span>Cost: <b>${escapeHtml(money(totals.cost))}</b></span>
        <span>Profit: <b>${escapeHtml(money(totals.profit))}</b></span>
      </div>
      <table>
        <thead><tr>${columns.map(([label]) => `<th>${escapeHtml(label)}</th>`).join('')}</tr></thead>
        <tbody>${body || `<tr><td colspan="${columns.length}">No report data matches these filters.</td></tr>`}</tbody>
      </table>
      <div class="sales-pdf-footer">Shayan's Kids Care - ${escapeHtml(title)}</div>
    </div>
  `

  const stage = document.createElement('div')
  stage.className = 'sales-pdf-stage'
  stage.innerHTML = documentHtml
  document.body.appendChild(stage)

  html2pdf().set({
    margin: 0.2,
    filename: `${mode}-sales-report.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, backgroundColor: '#ffffff', scrollX: 0, scrollY: 0 },
    jsPDF: { unit: 'in', format: 'a4', orientation: 'landscape' },
    pagebreak: { mode: ['css', 'legacy'], avoid: ['tr'] },
  }).from(stage.firstElementChild).save().finally(() => {
    document.body.removeChild(stage)
  })
}

function Summary({ totals }) {
  const cards = [
    ['Total Sales', money(totals.sales), CircleDollarSign, 'emerald'],
    ['Total Cost', money(totals.cost), Scale, 'slate'],
    ['Gross Profit', money(totals.profit), TrendingUp, totals.profit >= 0 ? 'emerald' : 'rose'],
    ['Outstanding', money(totals.outstanding), Landmark, totals.outstanding > 0 ? 'amber' : 'emerald'],
    ['Quantity Sold', number(totals.quantity), Boxes, 'indigo'],
  ]
  const tones = { emerald:'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300', slate:'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300', rose:'bg-rose-50 text-rose-700 dark:bg-rose-500/10 dark:text-rose-300', violet:'bg-violet-50 text-violet-700 dark:bg-violet-500/10 dark:text-violet-300', blue:'bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300', amber:'bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-300', cyan:'bg-cyan-50 text-cyan-700 dark:bg-cyan-500/10 dark:text-cyan-300', indigo:'bg-indigo-50 text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-300' }
  return <div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5 print:grid-cols-5">
    {cards.map(([label, value, Icon, tone]) => <div key={label} className="rounded-lg border border-slate-200 bg-white p-3 dark:border-emerald-400/15 dark:bg-emerald-950/25 print:p-2">
      <div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-wide text-slate-500 dark:text-emerald-100/55">{label}</p><p className="mt-1 text-base font-extrabold tabular-nums text-slate-900 dark:text-white print:text-sm">{value}</p></div><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg ${tones[tone]}`}><Icon size={16}/></span></div>
    </div>)}
  </div>
}

function Filters({ preset, setPreset, range, setRange, filters, setFilters, options, onRefresh }) {
  const control = 'rounded-lg border border-slate-300 dark:border-emerald-400/20 bg-white dark:bg-slate-900 px-3 py-2 text-sm text-slate-800 dark:text-white'
  const change = (key) => (event) => setFilters((old) => ({ ...old, [key]: event.target.value }))
  return <div className="rounded-2xl border border-slate-200/80 dark:border-emerald-400/15 bg-white dark:bg-emerald-950/25 p-4 shadow-[0_1px_3px_rgba(15,23,42,.04)] print:hidden">
    <div className="flex items-center gap-2 mb-4"><span className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-50 dark:bg-emerald-500/10"><Filter size={16} className="text-emerald-600 dark:text-emerald-300" /></span><div><h2 className="text-sm font-bold">Filters</h2><p className="text-[11px] text-slate-500">Narrow the report across all dimensions</p></div><button onClick={() => setFilters(emptyFilters)} className="ml-auto rounded-lg px-3 py-1.5 text-xs font-semibold text-slate-500 hover:bg-slate-100 hover:text-slate-800 dark:hover:bg-emerald-500/10">Reset all</button></div>
    <div className="grid sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6 gap-3">
      <select className={control} value={preset} onChange={(e) => { const value = e.target.value; setPreset(value); if (value !== 'custom') setRange(presetRange(value)) }}>
        <option value="today">Today</option><option value="yesterday">Yesterday</option><option value="this-week">This Week</option><option value="this-month">This Month</option><option value="last-month">Last Month</option><option value="custom">Custom Date Range</option>
      </select>
      <input className={control} type="date" value={range.start} onChange={(e) => { setPreset('custom'); setRange((r) => ({ ...r, start: e.target.value })) }} />
      <input className={control} type="date" value={range.end} onChange={(e) => { setPreset('custom'); setRange((r) => ({ ...r, end: e.target.value })) }} />
      <select className={control} value={filters.customer} onChange={change('customer')}><option value="">All customers</option>{options.customers.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select>
      <select className={control} value={filters.product} onChange={change('product')}><option value="">All products</option>{options.products.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select>
      <select className={control} value={filters.rep} onChange={change('rep')}><option value="">All sales reps</option>{options.reps.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select>
      <input className={control} placeholder="Invoice number" value={filters.invoice} onChange={change('invoice')} />
      <select className={control} value={filters.payment} onChange={change('payment')}><option value="">All payment types</option><option value="cash">Cash</option><option value="credit">Credit</option></select>
      <select className={control} value={filters.status} onChange={change('status')}><option value="">All invoice statuses</option><option value="paid">Paid</option><option value="partial">Partially paid</option><option value="unpaid">Unpaid</option></select>
      <button onClick={onRefresh} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white flex justify-center items-center gap-2"><RefreshCw size={15} />Apply date range</button>
    </div>
  </div>
}

function TableShell({ children }) { return <div className="overflow-x-auto rounded-2xl border border-slate-200/80 dark:border-emerald-400/15 bg-white dark:bg-emerald-950/25 shadow-[0_1px_3px_rgba(15,23,42,.04)] print:shadow-none">{children}</div> }
const Th = ({ children }) => <th className="sticky top-0 z-[1] whitespace-nowrap border-b border-slate-200/80 bg-slate-50/95 px-3 py-3.5 text-left text-[10px] font-extrabold uppercase tracking-wider text-slate-500 backdrop-blur dark:border-emerald-400/10 dark:bg-emerald-950/95 dark:text-emerald-100/55">{children}</th>
const Td = ({ children, className = '' }) => <td className={`whitespace-nowrap px-3 py-3.5 text-xs text-slate-700 dark:text-emerald-100/80 ${className}`}>{children}</td>

function DailyTable({ invoices, totals, expanded, setExpanded }) {
  const rows = invoices.flatMap((invoice) => invoice.invoice_items.map((item, index) => ({ invoice, item, index })))
  return <TableShell><table className="w-full"><thead className="bg-slate-50 dark:bg-emerald-900/30"><tr><Th></Th>{['Invoice No','Invoice Date','Customer','Sales Rep','Product','Product Code','Quantity Sold','Purchase Reference','Purchase Date Used','Unit Cost','Selling Price','Total Cost','Sales Amount','Gross Profit','Profit %','Cost Source','Payment Type','Invoice Status','Outstanding Balance','Created By'].map((x) => <Th key={x}>{x}</Th>)}</tr></thead>
    <tbody>{rows.map(({ invoice, item, index }) => {
      const cost = item.cost_price == null ? null : Number(item.cost_price) * Number(item.quantity || 0), sales = Number(item.total || 0), profit = cost == null ? null : sales - cost
      const margin = profit == null || sales <= 0 ? null : (profit / sales) * 100
      const open = expanded === invoice.id
      return <React.Fragment key={item.id}>
        <tr onClick={() => setExpanded(open ? null : invoice.id)} className="border-t border-slate-100 dark:border-emerald-400/10 hover:bg-emerald-50/50 dark:hover:bg-emerald-500/5 cursor-pointer">
          <Td>{index === 0 ? <span className="grid h-7 w-7 place-items-center rounded-lg bg-slate-100 text-slate-500 dark:bg-emerald-500/10">{open ? <ChevronDown size={15}/> : <ChevronRight size={15}/>}</span> : ''}</Td><Td className="font-bold text-slate-900 dark:text-white">{invoice.displayNumber}</Td><Td>{new Date(invoice.created_at).toLocaleDateString()}</Td><Td className="font-medium">{invoice.customers?.name || 'Walk-in'}</Td><Td>{invoice.employees?.name || '—'}</Td><Td>{item.productName || 'Unknown'}</Td><Td className="font-mono text-[11px]">{item.productCode || '—'}</Td><Td className="font-semibold">{number(item.quantity)}</Td><Td>{item.purchaseReference || '—'}</Td><Td>{item.purchaseDateUsed || '—'}</Td><Td>{item.cost_price == null ? 'Uncosted' : money(item.cost_price)}</Td><Td>{money(item.price)}</Td><Td>{cost == null ? '—' : money(cost)}</Td><Td className="font-bold text-slate-900 dark:text-white">{money(sales)}</Td><Td className={profit != null && profit < 0 ? 'font-semibold text-red-600' : 'font-semibold text-emerald-600'}>{profit == null ? '—' : money(profit)}</Td><Td>{margin == null ? '—' : `${margin.toFixed(2)}%`}</Td><Td><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{item.costSource || (item.cost_price == null ? 'Cost Not Available' : 'Product Cost')}</span></Td><Td><span className={`rounded-full px-2 py-1 text-[10px] font-bold capitalize ${invoice.payment_type==='cash'?'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300':'bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300'}`}>{invoice.payment_type}</span></Td><Td><span className={`rounded-full px-2 py-1 text-[10px] font-bold capitalize ${invoice.status==='paid'?'bg-emerald-50 text-emerald-700':invoice.status==='partial'?'bg-amber-50 text-amber-700':'bg-rose-50 text-rose-700'}`}>{invoice.status}</span></Td><Td className={invoice.outstanding>0?'font-bold text-amber-600':''}>{money(invoice.outstanding)}</Td><Td>{invoice.createdBy}</Td>
        </tr>
        {open && index === invoice.invoice_items.length - 1 && <tr><td colSpan="21" className="bg-slate-50 dark:bg-slate-900/50 p-5"><InvoiceDetail invoice={invoice} /></td></tr>}
      </React.Fragment>
    })}</tbody>
    <tfoot className="border-t-2 border-slate-200 bg-slate-50 font-bold dark:border-emerald-400/15 dark:bg-emerald-900/30"><tr><td colSpan="21" className="px-4 py-4"><div className="flex flex-wrap justify-end gap-8 text-xs"><span>Quantity: {number(totals.quantity)}</span><span>Total Sales: {money(totals.sales)}</span><span>Collected: {money(totals.cashCollected)}</span><span className="text-amber-600">Outstanding: {money(totals.outstanding)}</span></div></td></tr></tfoot>
  </table></TableShell>
}

function InvoiceDetail({ invoice }) {
  return <div className="grid lg:grid-cols-3 gap-5 text-sm">
    <div><h3 className="font-bold mb-2">Invoice Header</h3><p>{invoice.displayNumber} · {new Date(invoice.created_at).toLocaleString()}</p><p>Payment: <span className="capitalize">{invoice.payment_type}</span> · Status: <span className="capitalize">{invoice.status}</span></p><p>Sales rep: {invoice.employees?.name || 'Not assigned'}</p></div>
    <div><h3 className="font-bold mb-2">Customer Details</h3><p>{invoice.customers?.name || 'Walk-in customer'}</p><p>{invoice.customers?.phone || 'No phone'}</p><p>{invoice.customers?.address || 'No address'}</p></div>
    <div><h3 className="font-bold mb-2">Settlement</h3><p>Invoice total: {money(invoice.sales)}</p><p>Payments received: {money(invoice.paid)}</p><p className="font-bold text-amber-600">Outstanding: {money(invoice.outstanding)}</p></div>
    <div className="lg:col-span-3 overflow-x-auto"><table className="w-full"><thead><tr>{['Product','Quantity','Cost','Selling Price','Line Profit'].map((x) => <Th key={x}>{x}</Th>)}</tr></thead><tbody>{invoice.invoice_items.map((item) => { const profit = item.cost_price == null ? null : Number(item.total) - Number(item.cost_price) * Number(item.quantity); return <tr key={item.id} className="border-t"><Td>{item.products?.name}</Td><Td>{number(item.quantity)}</Td><Td>{item.cost_price == null ? 'Uncosted' : money(item.cost_price)}</Td><Td>{money(item.price)}</Td><Td>{profit == null ? '—' : money(profit)}</Td></tr> })}</tbody></table></div>
  </div>
}

function AggregateTable({ mode, rows }) {
  const definitions = {
    monthly: [['Month','label'],['Invoices','invoices'],['Quantity','quantity'],['Sales','sales','money'],['Cost','cost','money'],['Gross Profit','profit','money'],['Profit %','margin','percent'],['Payments','payments','money'],['Outstanding','outstanding','money']],
    customer: [['Customer','name'],['Phone','phone'],['Invoices','invoices'],['Quantity Purchased','quantity'],['Sales','sales','money'],['Payments','payments','money'],['Outstanding','outstanding','money'],['Credit Limit','creditLimit','money'],['Last Purchase','lastPurchase']],
    product: [['Product','name'],['Code','code'],['Opening Stock','opening'],['Purchased','purchased'],['Sold','sold'],['Current Stock','current'],['Cost Price','averageCost','money'],['Selling Price','sellingPrice','money'],['Revenue','revenue','money'],['Cost Value','cost','money'],['Gross Profit','profit','money'],['Profit %','margin','percent']],
    rep: [['Rep','name'],['Orders','orders'],['Invoices','invoices'],['Products Sold','products'],['Sales','sales','money'],['Gross Profit','profit','money'],['Commission','commission','money'],['Average Invoice','average','money']],
  }
  const cols = definitions[mode]
  return <TableShell><table className="w-full"><thead className="bg-slate-50 dark:bg-emerald-900/30"><tr>{cols.map(([label]) => <Th key={label}>{label}</Th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={row.id || row.label || i} className="border-t border-slate-100 dark:border-emerald-400/10 hover:bg-slate-50 dark:hover:bg-emerald-500/5">{cols.map(([label,key,type]) => <Td key={label} className={key === 'profit' ? (row[key] >= 0 ? 'text-emerald-600 font-semibold' : 'text-red-600 font-semibold') : ''}>{type === 'money' ? money(row[key]) : type === 'percent' ? `${Number(row[key] || 0).toFixed(2)}%` : (row[key] ?? '—')}</Td>)}</tr>)}</tbody></table>{!rows.length && <p className="p-10 text-center text-slate-500">No report data matches these filters.</p>}</TableShell>
}

function Charts({ mode, invoices, productRows }) {
  const base = {
    chart: {
      background: 'transparent',
      foreColor: '#94a3b8',
      toolbar: { show: false },
      fontFamily: 'inherit',
      animations: { easing: 'easeinout', speed: 450 },
    },
    colors: ['#34d399', '#22d3ee', '#a78bfa'],
    dataLabels: { enabled: false },
    grid: {
      borderColor: 'rgba(148, 163, 184, 0.14)',
      strokeDashArray: 4,
      padding: { left: 8, right: 14, top: 4, bottom: 0 },
    },
    legend: {
      labels: { colors: '#cbd5e1' },
      markers: { radius: 10 },
      fontWeight: 700,
    },
    noData: {
      text: 'No data for this range',
      align: 'center',
      verticalAlign: 'middle',
      style: { color: '#94a3b8', fontSize: '13px', fontFamily: 'inherit' },
    },
    plotOptions: {
      bar: { borderRadius: 6, columnWidth: '42%', distributed: false },
    },
    stroke: { curve: 'smooth', width: 3 },
    tooltip: { theme: 'dark' },
    xaxis: {
      axisBorder: { color: 'rgba(148, 163, 184, 0.22)' },
      axisTicks: { color: 'rgba(148, 163, 184, 0.22)' },
      labels: { style: { colors: '#94a3b8', fontSize: '11px', fontWeight: 600 } },
    },
    yaxis: {
      labels: { style: { colors: '#94a3b8', fontSize: '11px', fontWeight: 600 } },
    },
    theme: { mode: 'dark' },
  }
  const months = new Map()
  for (const inv of invoices) { const key = new Date(inv.created_at).toLocaleDateString(undefined, { month: 'short', year: '2-digit' }); const x = months.get(key) || { sales: 0, profit: 0 }; x.sales += inv.sales; x.profit += inv.profit; months.set(key, x) }
  const topProductsOptions = { ...base, xaxis: { ...base.xaxis, categories: productRows.slice(0, 8).map((x) => x.name) } }
  const monthlyOptions = {
    ...base,
    fill: { type: 'gradient', gradient: { shadeIntensity: 0.45, opacityFrom: 0.45, opacityTo: 0.06, stops: [0, 90, 100] } },
    xaxis: { ...base.xaxis, categories: [...months.keys()] },
  }
  if (mode === 'monthly') return <div className="print:hidden"><ChartCard title="Monthly Sales & Profit Trend"><Chart type="area" height={250} options={monthlyOptions} series={[{name:'Sales',data:[...months.values()].map(x=>x.sales)},{name:'Profit',data:[...months.values()].map(x=>x.profit)}]} /></ChartCard></div>
  if (mode === 'product') return <div className="print:hidden"><ChartCard title="Top Selling Products"><Chart type="bar" height={250} options={topProductsOptions} series={[{name:'Quantity',data:productRows.slice(0,8).map(x=>x.sold)}]} /></ChartCard></div>
  return null
}
function ChartCard({ title, children }) { return <div className="rounded-lg border border-slate-200 bg-white p-4 dark:border-emerald-400/15 dark:bg-emerald-950/25"><h3 className="mb-3 text-sm font-bold text-slate-900 dark:text-white">{title}</h3>{children}</div> }

export default function SalesReportsPage({ initialMode = 'daily' }) {
  const { user } = useAuth()
  const [mode, setMode] = useState(initialMode)
  const [preset, setPreset] = useState(initialMode === 'daily' ? 'today' : 'this-month')
  const [range, setRange] = useState(() => presetRange(initialMode === 'daily' ? 'today' : 'this-month'))
  const [filters, setFilters] = useState(emptyFilters)
  const [raw, setRaw] = useState({ invoices: [], payments: [], products: [], variants: [], purchases: [], reportRows: [], rpcError: '', orders: [] })
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [expanded, setExpanded] = useState(null)
  const generatedBy = user?.user_metadata?.display_name || user?.email?.split('@')[0] || 'System user'

  const load = async () => { setLoading(true); setError(''); try { setRaw(await fetchReportData(range.start, range.end)) } catch (e) { setError(e.message || 'Unable to load sales report') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])

  const model = useMemo(() => {
    const paymentByInvoice = new Map()
    for (const p of raw.payments) paymentByInvoice.set(String(p.invoice_id), (paymentByInvoice.get(String(p.invoice_id)) || 0) + Number(p.amount || 0))
    const variantsById = new Map((raw.variants || []).map((variant) => [String(variant.id), variant]))
    const productsById = new Map((raw.products || []).map((product) => [String(product.id), product]))
    const reportByItem = new Map((raw.reportRows || []).map((row) => [String(row.invoice_item_id), row]))
    const purchaseCostsByProduct = new Map()
    for (const purchase of raw.purchases || []) {
      const productId = purchase.product_id
      if (!productId) continue
      const dateValue = purchase.purchases?.date || purchase.purchases?.created_at || ''
      const entry = { date: new Date(dateValue || 0), cost: Number(purchase.cost || 0), quantity: Number(purchase.quantity || 0) }
      if (!purchaseCostsByProduct.has(String(productId))) purchaseCostsByProduct.set(String(productId), [])
      purchaseCostsByProduct.get(String(productId)).push(entry)
    }
    for (const entries of purchaseCostsByProduct.values()) entries.sort((a, b) => a.date - b.date)
    const getProductCost = (productId, saleDateValue) => {
      const entries = purchaseCostsByProduct.get(String(productId))
      if (!entries?.length) return null
      const saleDate = new Date(saleDateValue)
      let cost = entries[entries.length - 1].cost
      for (const entry of entries) {
        if (entry.date <= saleDate) cost = entry.cost
      }
      return cost
    }
    let invoices = raw.invoices.map((inv) => {
      const normalizedItems = (inv.invoice_items || []).map((item) => {
        const report = reportByItem.get(String(item.id))
        const variant = variantsById.get(String(item.variant_id))
        const productId = item.product_id || variant?.product_id
        const product = productsById.get(String(productId))
        const productCost = getProductCost(productId, inv.created_at)
        const lineCost = report ? report.unit_cost : item.cost_price
        return { ...item, product_id: productId, quantity: report?.quantity_sold ?? item.quantity, price: report?.unit_selling_price ?? item.price, total: report?.sales_amount ?? item.total, cost_price: lineCost ?? productCost, purchaseReference: report?.purchase_reference, purchaseDateUsed: report?.purchase_date_used, costSource: report?.cost_source || (lineCost == null && productCost != null ? 'Product Cost' : undefined), returnedQuantity: report?.returned_quantity || 0, products: product, productName: report?.product_name || product?.name, productCode: report?.product_code || product?.code, barcode: variant?.barcode_number, variantLabel: variant ? [variant.size, variant.color].filter(Boolean).join(' / ') : '' }
      })
      const netLineSales = normalizedItems.reduce((sum, item) => sum + Number(item.total || 0), 0)
      const sales = raw.reportRows?.length ? netLineSales : Number(inv.total_amount || 0), paid = inv.reportPaid != null ? Math.min(sales, Number(inv.reportPaid || 0)) : inv.payment_type === 'cash' ? sales : Math.min(sales, paymentByInvoice.get(String(inv.id)) || 0)
      const cost = normalizedItems.reduce((s, x) => s + (x.cost_price == null ? 0 : Number(x.cost_price) * Number(x.quantity || 0)), 0)
      const outstanding = inv.reportOutstanding != null ? Number(inv.reportOutstanding || 0) : Math.max(0, sales - paid), status = outstanding <= .01 ? 'paid' : paid > 0 ? 'partial' : 'unpaid'
      const hasCost = normalizedItems.some((item) => item.cost_price != null)
      return { ...inv, invoice_items: normalizedItems, sales, paid, outstanding, cost, hasCost, profit: hasCost ? sales - cost : 0, status, displayNumber: `INV-${String(inv.invoice_number || inv.id).padStart(4,'0')}`, createdBy: 'System' }
    })
    invoices = invoices.filter((x) => (!filters.customer || String(x.customer_id) === filters.customer) && (!filters.rep || String(x.rep_id) === filters.rep) && (!filters.invoice || x.displayNumber.toLowerCase().includes(filters.invoice.toLowerCase())) && (!filters.payment || x.payment_type === filters.payment) && (!filters.status || x.status === filters.status) && (!filters.product || x.invoice_items.some((i) => String(i.product_id) === filters.product)))
    if (filters.product) invoices = invoices.map((x) => ({ ...x, invoice_items: x.invoice_items.filter((i) => String(i.product_id) === filters.product) }))
    const quantity = invoices.reduce((s,x)=>s+x.invoice_items.reduce((a,i)=>a+Number(i.quantity||0),0),0), sales=invoices.reduce((s,x)=>s+x.sales,0), cost=invoices.reduce((s,x)=>s+x.cost,0), profit=sales-cost
    const missingCost = invoices.reduce((sum, invoice) => sum + invoice.invoice_items.filter((item) => item.cost_price == null).length, 0)
    const totals = { sales, cost, profit, hasCost:invoices.some(x=>x.hasCost), margin:sales?profit/sales*100:0, invoices:invoices.length, cash:invoices.filter(x=>x.payment_type==='cash').reduce((s,x)=>s+x.sales,0), credit:invoices.filter(x=>x.payment_type==='credit').reduce((s,x)=>s+x.sales,0), outstanding:invoices.reduce((s,x)=>s+x.outstanding,0), average:invoices.length?sales/invoices.length:0, quantity, missingCost, cashCollected:invoices.reduce((s,x)=>s+x.paid,0) }
    const group = (keyFn, seedFn) => { const map=new Map(); for(const inv of invoices){const key=keyFn(inv);const x=map.get(key)||seedFn(inv,key);x.invoices++;x.quantity+=inv.invoice_items.reduce((s,i)=>s+Number(i.quantity||0),0);x.sales+=inv.sales;x.cost+=inv.cost;x.profit+=inv.profit;x.payments+=inv.paid;x.outstanding+=inv.outstanding;x.lastPurchase=!x.lastPurchase||inv.created_at>x.lastPurchase?inv.created_at:x.lastPurchase;map.set(key,x)} return [...map.values()].map(x=>({...x,margin:x.sales?x.profit/x.sales*100:0,lastPurchase:x.lastPurchase?new Date(x.lastPurchase).toLocaleDateString():'—'})) }
    const monthly=group(x=>x.created_at.slice(0,7),(x,key)=>({id:key,label:new Date(`${key}-02`).toLocaleDateString(undefined,{month:'long',year:'numeric'}),invoices:0,quantity:0,sales:0,cost:0,profit:0,payments:0,outstanding:0}))
    const customer=group(x=>String(x.customer_id||'walk-in'),x=>({id:x.customer_id||'walk-in',name:x.customers?.name||'Walk-in',phone:x.customers?.phone||'—',creditLimit:x.customers?.credit_limit||0,invoices:0,quantity:0,sales:0,cost:0,profit:0,payments:0,outstanding:0}))
    const ordersByRep = new Map(); for (const order of raw.orders || []) ordersByRep.set(String(order.rep_id || 'unassigned'), (ordersByRep.get(String(order.rep_id || 'unassigned')) || 0) + 1)
    const rep=group(x=>String(x.rep_id||'unassigned'),x=>({id:x.rep_id||'unassigned',name:x.employees?.name||'Unassigned',orders:0,invoices:0,quantity:0,products:0,sales:0,cost:0,profit:0,payments:0,outstanding:0})).map(x=>({...x,orders:ordersByRep.get(String(x.id))||0,products:x.quantity,commission:x.sales*getCommissionRate(x.name),average:x.invoices?x.sales/x.invoices:0}))
    const productMap=new Map(raw.products.map(p=>[String(p.id),{id:p.id,name:p.name,code:p.code||'—',opening:0,purchased:0,sold:0,current:Number(p.stock||0),averageCost:0,sellingPrice:Number(p.price||0),revenue:0,cost:0,profit:0,_costQty:0,_costValue:0,_sellQty:0}]))
    for(const v of raw.variants||[]){const x=productMap.get(String(v.product_id));if(!x)continue;x.current+=Number(v.stock_quantity||0);x.sellingPrice+=Number(v.selling_price||0);x._sellQty++}
    for(const p of raw.purchases){const variant=variantsById.get(String(p.variant_id));const productId=p.product_id||variant?.product_id;const x=productMap.get(String(productId));if(!x)continue;const qty=Number(p.quantity||0);const purchaseDate=p.purchases?.purchase_date?.slice(0,10)||p.purchases?.date;if(purchaseDate>=range.start)x.purchased+=qty;x._costQty+=qty;x._costValue+=qty*Number(p.cost_price??p.cost??0)}
    for(const inv of invoices)for(const i of inv.invoice_items){const x=productMap.get(String(i.product_id));if(!x)continue;const q=Number(i.quantity||0),revenue=Number(i.total||0),cost=i.cost_price==null?0:Number(i.cost_price)*q;x.sold+=q;x.revenue+=revenue;x.cost+=cost;x.profit+=revenue-cost}
    const product=[...productMap.values()].filter(x=>x.sold||x.purchased).map(x=>({...x,opening:x.current+x.sold-x.purchased,averageCost:x._costQty?x._costValue/x._costQty:x.averageCost,sellingPrice:x._sellQty?x.sellingPrice/x._sellQty:x.sellingPrice,margin:x.revenue?x.profit/x.revenue*100:0})).sort((a,b)=>b.sold-a.sold)
    return { invoices, totals, monthly, customer, rep, product }
  }, [raw, filters, range.start])

  const options = useMemo(() => ({ customers:[...new Map(raw.invoices.filter(x=>x.customers).map(x=>[x.customers.id,x.customers])).values()].sort((a,b)=>a.name.localeCompare(b.name)), products:raw.products, reps:[...new Map(raw.invoices.filter(x=>x.employees).map(x=>[x.employees.id,x.employees])).values()].sort((a,b)=>a.name.localeCompare(b.name)) }), [raw])
  const modes = [['daily','Daily Sales'],['monthly','Monthly Sales'],['customer','By Customer'],['product','By Product'],['rep','By Sales Rep']]
  const title = modes.find(x=>x[0]===mode)?.[1] + ' Report'
  const exportRows = mode==='daily' ? model.invoices.flatMap(x=>x.invoice_items.map(i=>({Invoice:x.displayNumber,'Invoice Date':x.created_at.slice(0,10),Customer:x.customers?.name,'Sales Rep':x.employees?.name,'Product Code':i.productCode||i.products?.code,'Product Name':i.productName||i.products?.name,'Quantity Sold':i.quantity,'Returned Quantity':i.returnedQuantity,'Purchase Reference':i.purchaseReference||'','Purchase Date Used':i.purchaseDateUsed||'','Unit Cost':i.cost_price??'','Unit Selling Price':i.price,'Total Cost':i.cost_price==null?0:Number(i.cost_price)*Number(i.quantity),'Sales Amount':i.total,'Gross Profit':Number(i.total)-Number(i.cost_price||0)*Number(i.quantity),'Profit Margin %':Number(i.total)>0?(Number(i.total)-Number(i.cost_price||0)*Number(i.quantity))/Number(i.total)*100:0,'Cost Source':i.costSource||(i.cost_price==null?'Cost Not Available':'Stored Cost'),'Payment Type':x.payment_type,Status:x.status,'Outstanding Balance':x.outstanding}))) : model[mode]
  const doCsv = () => { const csv=XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(exportRows)); const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`${mode}-sales-report.csv`;a.click();URL.revokeObjectURL(a.href) }

  if (loading) return <LoadingSkeleton />
  return <div id="sales-report" className="space-y-5 print:text-black">
    <PrintHeader title={title} generatedBy={generatedBy} range={range} />
    <header className="rounded-lg border border-slate-200 bg-white p-4 dark:border-emerald-400/15 dark:bg-emerald-950/25 print:hidden"><div className="flex flex-col gap-4 xl:flex-row xl:items-center"><div><p className="text-[10px] font-bold uppercase tracking-widest text-emerald-700 dark:text-emerald-300">Sales reports</p><h1 className="mt-1 text-xl font-bold text-slate-900 dark:text-white">Sales Reports</h1><p className="mt-0.5 text-sm text-slate-500 dark:text-emerald-100/65">Detailed sales, historical cost, profitability and receivables.</p></div><div className="xl:ml-auto inline-flex w-fit flex-wrap gap-1 rounded-lg border border-slate-200 bg-slate-50 p-1 dark:border-emerald-400/15 dark:bg-emerald-950/40">{modes.map(([key,label])=><button key={key} onClick={()=>setMode(key)} className={`rounded-md px-3 py-1.5 text-xs font-bold ${mode===key?'bg-emerald-600 text-white':'text-slate-600 hover:bg-white dark:text-emerald-100/75 dark:hover:bg-emerald-900'}`}>{label}</button>)}</div></div></header>
    <Filters {...{preset,setPreset,range,setRange,filters,setFilters,options,onRefresh:load}} />
    {error && <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700"><b>Report could not load:</b> {error}<br/><span className="text-xs">If the error mentions cost_price, run supabase/sales_reports_historical_cost.sql in Supabase.</span></div>}
    <Summary totals={model.totals} />
    <div className="flex flex-wrap justify-between items-center gap-3 print:hidden"><div><div className="flex items-center gap-2"><span className="h-5 w-1 rounded-full bg-emerald-500"/><h2 className="font-extrabold text-lg text-slate-900 dark:text-white">{title}</h2></div><p className="ml-3 mt-0.5 text-xs text-slate-500">{range.start} to {range.end} <span className="mx-1">·</span> {model.invoices.length} invoices</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>window.print()} className="report-action"><Printer size={15}/>Print</button><button onClick={()=>exportSalesReportPDF({ mode, title, range, generatedBy, model, exportRows })} className="report-action"><Download size={15}/>PDF</button><button onClick={()=>exportToExcel(exportRows,`${mode}-sales-report.xlsx`,'Sales Report')} className="report-action"><FileSpreadsheet size={15}/>Excel</button><button onClick={doCsv} className="report-action"><Download size={15}/>CSV</button></div></div>
    {mode==='daily'?<DailyTable invoices={model.invoices} totals={model.totals} expanded={expanded} setExpanded={setExpanded}/>:<AggregateTable mode={mode} rows={model[mode]} />}
    <Charts mode={mode} invoices={model.invoices} productRows={model.product} />
    <div className="hidden print:flex justify-between border-t pt-3 text-[10px]"><span>Shayan's Kids Care · {title}</span><span className="print-page-number">Page</span></div>
  </div>
}
